import type { Locale } from "@/lib/i18n";

const en = {
  common: {
    adminPublishing: "Admin publishing",
    channelPublishing: "Channel publishing",
    superAdmin: "Super admin",
    moderation: "Moderation",
    backToAdmin: "Back to admin",
    backToGames: "Back to games",
    backToChannels: "Back to channels",
    backToChannel: "Back to channel",
    edit: "Edit",
    delete: "Delete",
    remove: "Remove",
    cancel: "Cancel",
    saveChanges: "Save changes",
    actionFailed: "Action failed",
    done: "Done",
    couldNotDelete: "Could not delete",
    couldNotSave: "Could not save",
    networkError: "Network error. Try again.",
    deleteFailed: (status: number) => `Delete failed (${status})`,
    loading: "Loading...",
    empty: "-",
  },
  dashboard: {
    eyebrow: "Private workspace",
    title: "Admin workspace",
    description:
      "A focused staff console for reviewing community activity, preparing updates, and checking public pages before changes go live.",
    accessTitle: "Access",
    accessDescription: "Staff controls are private and hidden from public navigation.",
    toolsTitle: "Admin tools enabled",
    toolsDescription:
      "Your account can use the private tools below. Every write action is scoped, recorded, and reflected on the matching public page.",
    signInTitle: "Sign in required",
    signInDescription:
      "Staff tools are not shown to public users. Sign in with Discord to access admin workflows.",
    signInAction: "Sign in",
    inactiveTitle: "Admin access is not active",
    inactiveDescription:
      "Add Discord user IDs to EWC_DASHBOARD_ADMIN_DISCORD_IDS before enabling dashboard management tools.",
    roleScoped: "Scoped admin",
    quickNewPost: "New post",
    quickComments: "Review comments",
    quickGames: "Manage games",
    workflowEyebrow: "Daily flow",
    workflowTitle: "Publish with fewer missed steps",
    workflowDescription:
      "Use the dashboard as a short loop: moderate, prepare, then verify the public view before the community sees the update.",
    workflowItems: [
      {
        title: "Review the queue",
        description:
          "Clear pending comments and flagged links before new posts draw traffic.",
      },
      {
        title: "Prepare the update",
        description:
          "Draft or edit the post with the correct game, media channel, and language.",
      },
      {
        title: "Verify after publishing",
        description:
          "Check the public page, related cards, and audit log after the change goes live.",
      },
    ],
    scopeTitle: "Your current scope",
    scopeDescription:
      "A quick read on what this account can manage right now.",
    scope: {
      posts: "Visible posts",
      drafts: "Drafts waiting",
      games: "Managed games",
    },
    workspaceTitle: "Workspace shortcuts",
    workspaceDescription:
      "Jump into the focused tools for content, moderation, game pages, and staff operations.",
    stats: {
      posts: "Posts",
      postsDescription: "Updates visible to the staff member.",
      published: "Published",
      publishedDescription: "Public updates currently live.",
      drafts: "Drafts",
      draftsDescription: "Work that still needs review.",
      games: "Games",
      gamesDescription: "Game pages in this admin scope.",
    },
    links: {
      gamesTitle: "Game pages",
      gamesDescription: "Edit the games you manage.",
      mediaTitle: "Media channels",
      mediaDescription: "Edit the media channels you manage.",
      commentsTitle: "Comments",
      commentsDescription: "Review flagged and pending community comments.",
      teamTitle: "Admin team",
      teamDescription: "Add admins and assign their games and channels.",
      auditTitle: "Audit log",
      auditDescription: "View recent dashboard mutations by all admins.",
      usersTitle: "Users",
      usersDescription: "Find members, review their activity, and block abusers.",
      partnersTitle: "Partners",
      partnersDescription: "Review sponsor inquiries and manage partner recognition.",
      streamsTitle: "Co-streams",
      streamsDescription: "Manage live Twitch, Kick, YouTube, and SOOP co-stream channels.",
    },
    newsTitle: "News & posts",
    newsDescription: "Draft, edit, publish, and remove the updates shown on game pages.",
  },
  newsList: {
    newPost: "New post",
    editPost: "Edit post",
    postsCount: (count: number) => `${count} post${count === 1 ? "" : "s"}`,
    headers: {
      title: "Title",
      owner: "Owner",
      content: "Content",
      status: "Status",
      updated: "Updated",
      actions: "Actions",
    },
    mediaBadge: "Media",
    translatedContent: "English + Arabic",
    sharedContent: (locale: string) => `Shared ${locale.toUpperCase()}`,
    published: "Published",
    draft: "Draft",
    empty: "No posts yet. Create your first community update.",
    deleteConfirm: "Delete this post? This cannot be undone.",
    deleteTitle: "Delete this post?",
    deleteDescription:
      "This removes the post from the admin list and public pages. This action cannot be undone.",
    deleteAction: "Delete post",
    deleteSuccess: "Post deleted successfully.",
  },
  games: {
    title: "Game pages",
    newTitle: "New game",
    editTitle: "Edit game",
    description:
      "Add, edit, reorder, or remove the games shown on the public site. Deleting a game also removes its news posts.",
    count: (count: number) => `${count} game${count === 1 ? "" : "s"}`,
    newAction: "New game",
    empty: "No games yet. Add your first game.",
    deleteConfirm: (title: string) =>
      `Delete "${title}"? This also deletes its news posts and cannot be undone.`,
    moveUp: "Move up",
    moveDown: "Move down",
  },
  media: {
    title: "Media channels",
    newTitle: "New media channel",
    editTitle: "Edit media channel",
    postsTitle: "Posts",
    descriptionSuper:
      "The esports media accounts shown in the public directory. Create, edit, reorder, or remove channels.",
    descriptionScoped:
      "The esports media accounts shown in the public directory. You can edit your assigned channels.",
    channelPostsDescription:
      "Articles published by this channel. They appear on the channel's public page and post to its Discord channel when published.",
    count: (count: number) => `${count} channel${count === 1 ? "" : "s"}`,
    linkCount: (count: number) => `${count} link${count === 1 ? "" : "s"}`,
    newAction: "New channel",
    empty: "No media channels yet.",
    deleteConfirm: (name: string) => `Delete "${name}"? This cannot be undone.`,
    moveUp: "Move up",
    moveDown: "Move down",
  },
  comments: {
    title: "Comments",
    description: "Review flagged and pending comments. Every action is recorded in the audit log.",
    filters: {
      pending: "Pending",
      flagged: "Flagged",
      reported: "Reported",
      visible: "Visible",
      hidden: "Hidden",
      rejected: "Rejected",
      deleted: "Deleted",
    },
    actions: {
      approve: "Approve",
      reject: "Reject",
      hide: "Hide",
      restore: "Restore",
      delete: "Delete",
    },
    done: {
      approve: "Comment approved successfully.",
      reject: "Comment rejected successfully.",
      hide: "Comment hidden successfully.",
      restore: "Comment restored successfully.",
      delete: "Comment deleted successfully.",
      fallback: "Comment updated successfully.",
    },
    noComments: (filter: string) => `No comments in "${filter}".`,
    authorFallback: "Unknown author",
    onPost: "on",
    postFallback: (id: number) => `post #${id}`,
    reply: "reply",
    profanity: "profanity",
    links: "links",
    reports: (n: number) => `${n} ${n === 1 ? "report" : "reports"}`,
    deleteTitle: "Delete this comment?",
    deleteDescription:
      "This removes the comment from public threads while keeping the moderation history.",
  },
  users: {
    title: "Users",
    description: "Members who signed in to the dashboard, newest first. Search by name or Discord id.",
    searchPlaceholder: "Search by name or Discord id",
    searchAction: "Search",
    headers: {
      member: "Member",
      discordId: "Discord id",
      joined: "Joined",
      lastActive: "Last active",
      comments: "Comments",
      likes: "Likes",
      ewcLinked: "EWC linked",
      status: "Status",
    },
    ewcLinkedBadge: "EWC linked",
    blockedBadge: "Blocked",
    empty: "No users match.",
    previous: "Previous",
    next: "Next",
    nameFallback: "Unnamed member",
    detail: {
      activityTitle: "Activity",
      comments: "Comments",
      likes: "Likes",
      lastActive: "Last active",
      joined: "Joined",
      never: "Never",
      commentsTitle: "Their comments",
      noComments: "This member has not commented yet.",
    },
    block: {
      blockAction: "Block member",
      unblockAction: "Unblock member",
      reasonPlaceholder: "Reason (optional)",
      blockedTitle: "Blocked",
      blockedBy: "Blocked by",
      blockedReason: "Reason",
      confirmTitle: "Block this member?",
      confirmDescription:
        "They will no longer be able to comment or like. Existing comments stay until you moderate them.",
      confirmAction: "Block",
      blockedNotice: "Member blocked.",
      unblockedNotice: "Member unblocked.",
    },
    moderation: {
      approve: "Approve",
      hide: "Hide",
      delete: "Delete",
      done: "Comment updated.",
      deleteTitle: "Delete this comment?",
      deleteDescription:
        "This removes the comment from public threads while keeping the moderation history.",
    },
  },
  audit: {
    title: "Audit log",
    description: "The 100 most recent dashboard mutations. Read-only; pagination is deferred.",
    recentTitle: "Recent activity",
    recentDescription:
      "Every successful admin write is recorded here with the actor, action, and target.",
    empty: "No audit entries yet.",
    headers: {
      time: "Time",
      actor: "Actor",
      action: "Action",
      target: "Target",
    },
  },
  team: {
    title: "Admin team",
    description:
      "Add admins by Discord ID and assign exactly which games and media channels each one can manage. Super admins are configured via the EWC_DASHBOARD_SUPER_ADMIN_DISCORD_IDS environment variable.",
    addCardTitle: "Add admin",
    discordId: "Discord user ID",
    discordIdPlaceholder: "e.g. 100000000000000001",
    discordIdDescription: "The member's Discord account (snowflake) ID.",
    displayName: "Display name",
    displayNamePlaceholder: "e.g. Echo MENA team",
    gamesManage: "Games they can manage",
    mediaManage: "Media channels they can manage",
    games: "Games",
    media: "Media channels",
    addAction: "Add admin",
    adminsCount: (count: number) => `Admins (${count})`,
    noneAvailable: "None available",
    noName: "(no name)",
    noAssignments: "No assignments yet",
    empty: "No regular admins yet. Add one above to delegate specific games or channels.",
    discordIdRequired: "Discord ID is required",
    addFailed: "Failed to add admin",
    saveFailed: "Failed to save",
    removeConfirm: (name: string) => `Remove ${name} from the admin team?`,
  },
  streams: {
    addTitle: "Add co-streamer channels",
    addDescription:
      "Add Twitch, Kick, YouTube, and SOOP for one streamer in a single action. Pick which platform should be the default embed.",
    couldNotSave: "Could not save",
    platformError: (platform: string, status: number) => `Could not add ${platform} (${status}).`,
    updateError: (label: string) => `Could not update ${label}.`,
    networkError: "Network error. Try again.",
    validation: {
      platformRequired: "Add at least one platform handle or URL.",
      labelRequired: "A display label is required when adding multiple platform channels for the same streamer.",
      gameRequired: "Pick at least one game for a per-game channel.",
    },
    labels: {
      streamer: "Streamer display label",
      defaultPlatform: "Default embed platform",
      platformPlaceholder: "Default platform",
      handleOrUrl: (platform: string) => `${platform} handle or URL`,
      scope: "Scope",
      language: "Language (optional)",
      team: "Team name",
      matchExternalId: "Match external ID",
      editLabel: "Edit label",
      editLanguage: "Edit language",
    },
    placeholders: {
      streamer: "OWBrain",
      twitch: "owbrain or twitch.tv/owbrain",
      channelUrl: (platform: string) => `${platform} channel URL`,
      language: "en or ar",
      team: "Twisted Minds",
      matchExternalId: "sgg:104353062 or Match:ID_...",
    },
    embedHelp: "Embeds are available for Twitch, Kick, and live YouTube channels. SOOP is saved as a link.",
    games: "Games",
    gameTagsOptional: "Game tags (optional)",
    selectedCount: (count: number) => `${count} selected`,
    gamePickerHelp:
      "Pick with buttons instead of typing separators. One streamer can appear under multiple games.",
    scopeLabels: {
      ewc: "EWC official list",
      game: "Per game",
      team: "Per team",
      match: "Per match",
    },
    addAction: "Add streamer",
    channelsCount: (count: number) => `${count} channel${count === 1 ? "" : "s"}`,
    streamersCount: (count: number) => `${count} streamer${count === 1 ? "" : "s"}`,
    platformsCount: (count: number) => `${count} platform${count === 1 ? "" : "s"}`,
    inactive: "Inactive",
    group: (key: string) => `Group: ${key}`,
    defaultBadge: "Default",
    setDefault: "Set default",
    disable: "Disable",
    enable: "Enable",
    save: "Save",
    cancel: "Cancel",
    remove: "Remove",
    removeStreamer: "Remove streamer",
    empty: "No channels yet.",
    removeTitle: "Remove co-stream channel?",
    removeDescription: (platform: string, handle: string) =>
      `This removes ${platform} / ${handle} from the co-stream registry.`,
    removeStreamerTitle: "Remove streamer?",
    removeStreamerDescription: (label: string, count: number) =>
      `This removes all ${count} platform channel${count === 1 ? "" : "s"} for ${label} from this scope.`,
  },
  editor: {
    titleLabel: "Title",
    nameLabel: "Name",
    descriptionLabel: "Description",
    ownerLabel: "Owner",
    englishPlaceholder: "English",
    arabicPlaceholder: "Arabic",
    urlSlug: "URL slug",
    fixedSlug: "The slug is fixed once created.",
    fixedGameSlug: "The slug is fixed once created (it's the public URL).",
    gamePublicUrl: (slug: string) => `Public URL: /games/${slug || "your-slug"}`,
    mediaPublicUrl: (slug: string) => `Public URL: /media/${slug || "your-slug"}`,
    titleDescription: "Shown as the game name (required in both languages).",
    statusBadge: "Status badge",
    statusDescription: 'The small badge, e.g. "Coverage ready".',
    discordNewsChannel: "Discord news channel ID",
    discordNewsDescription:
      "Optional. Published news for this game auto-posts here. Leave blank to use the server's default news channel.",
    focusTags: "Focus tags",
    englishTag: "English tag",
    arabicTag: "Arabic tag",
    removeTag: "Remove tag",
    addTag: "Add tag",
    focusDescription: "Short topics shown on the game page.",
    createGame: "Create game",
    logoImage: "Logo image (optional)",
    upload: "Upload",
    uploadFailed: "Upload failed",
    socialLinks: "Social & platform links",
    removeLink: "Remove link",
    addLink: "Add link",
    linksDescription: "Only http(s) links are saved.",
    discordChannelOptional: "Discord channel ID (optional)",
    invalidDiscordChannel: "Enter a valid Discord channel ID (17-20 digits).",
    mediaDiscordDescription:
      "Set this to auto-post the channel to Discord (announced on create, edited on changes). Leave empty to keep it off Discord.",
    createChannel: "Create channel",
  },
};

const ar: typeof en = {
  common: {
    adminPublishing: "نشر الإدارة",
    channelPublishing: "نشر القناة",
    superAdmin: "إدارة عليا",
    moderation: "الإشراف",
    backToAdmin: "العودة إلى الإدارة",
    backToGames: "العودة إلى الألعاب",
    backToChannels: "العودة إلى القنوات",
    backToChannel: "العودة إلى القناة",
    edit: "تعديل",
    delete: "حذف",
    remove: "إزالة",
    cancel: "إلغاء",
    saveChanges: "حفظ التغييرات",
    actionFailed: "تعذر تنفيذ الإجراء",
    done: "تم",
    couldNotDelete: "تعذر الحذف",
    couldNotSave: "تعذر الحفظ",
    networkError: "حدث خطأ في الاتصال. حاول مرة أخرى.",
    deleteFailed: (status: number) => `فشل الحذف (${status})`,
    loading: "جار التحميل...",
    empty: "-",
  },
  dashboard: {
    eyebrow: "مساحة خاصة",
    title: "لوحة إدارة المحتوى",
    description:
      "لوحة مركزة للفريق لمراجعة نشاط المجتمع، وتجهيز التحديثات، والتحقق من الصفحات العامة قبل نشر أي تغيير.",
    accessTitle: "الصلاحيات",
    accessDescription: "أدوات الفريق خاصة ولا تظهر في التصفح العام.",
    toolsTitle: "أدوات الإدارة مفعلة",
    toolsDescription:
      "يمكن لهذا الحساب استخدام الأدوات الخاصة أدناه. كل إجراء تعديل محدود بالصلاحيات، ومسجل، وينعكس على الصفحة العامة المناسبة.",
    signInTitle: "تسجيل الدخول مطلوب",
    signInDescription:
      "أدوات الفريق لا تظهر للمستخدمين العامين. سجل دخولك بديسكورد للوصول إلى أدوات الإدارة.",
    signInAction: "تسجيل الدخول",
    inactiveTitle: "صلاحية الإدارة غير مفعلة",
    inactiveDescription:
      "أضف معرفات مستخدمي ديسكورد إلى EWC_DASHBOARD_ADMIN_DISCORD_IDS قبل تفعيل أدوات إدارة اللوحة.",
    roleScoped: "إداري مخصص",
    quickNewPost: "منشور جديد",
    quickComments: "مراجعة التعليقات",
    quickGames: "إدارة الألعاب",
    workflowEyebrow: "مسار العمل اليومي",
    workflowTitle: "انشر التحديثات بدون خطوات ناقصة",
    workflowDescription:
      "استخدم اللوحة كمسار قصير: راجع، جهز، ثم تحقق من العرض العام قبل أن يرى المجتمع التحديث.",
    workflowItems: [
      {
        title: "راجع قائمة الانتظار",
        description:
          "راجع التعليقات المعلقة والروابط التي تحتاج موافقة قبل أن يجذب أي منشور جديد الزوار.",
      },
      {
        title: "جهز التحديث",
        description:
          "اكتب المنشور أو عدله مع اختيار اللعبة أو قناة الإعلام واللغة المناسبة.",
      },
      {
        title: "تحقق بعد النشر",
        description:
          "راجع الصفحة العامة والبطاقات المرتبطة وسجل التدقيق بعد ظهور التغيير.",
      },
    ],
    scopeTitle: "نطاق صلاحيتك الحالي",
    scopeDescription: "نظرة سريعة على ما يمكن لهذا الحساب إدارته الآن.",
    scope: {
      posts: "المنشورات المرئية",
      drafts: "المسودات المنتظرة",
      games: "الألعاب المدارة",
    },
    workspaceTitle: "اختصارات العمل",
    workspaceDescription:
      "انتقل بسرعة إلى أدوات المحتوى، الإشراف، صفحات الألعاب، وعمليات الفريق.",
    stats: {
      posts: "المنشورات",
      postsDescription: "التحديثات التي تظهر لهذا الإداري.",
      published: "منشور",
      publishedDescription: "تحديثات منشورة للعامة حاليا.",
      drafts: "مسودات",
      draftsDescription: "أعمال ما زالت تحتاج مراجعة.",
      games: "الألعاب",
      gamesDescription: "صفحات الألعاب ضمن صلاحية هذا الإداري.",
    },
    links: {
      gamesTitle: "صفحات الألعاب",
      gamesDescription: "عدّل الألعاب التي تديرها.",
      mediaTitle: "قنوات الإعلام",
      mediaDescription: "عدّل قنوات الإعلام التي تديرها.",
      commentsTitle: "التعليقات",
      commentsDescription: "راجع تعليقات المجتمع المعلقة أو التي تحتاج مراجعة.",
      teamTitle: "فريق الإدارة",
      teamDescription: "أضف الإداريين وحدد ألعابهم وقنواتهم.",
      auditTitle: "سجل التدقيق",
      auditDescription: "استعرض آخر تغييرات لوحة التحكم من جميع الإداريين.",
      usersTitle: "المستخدمون",
      usersDescription: "ابحث عن الأعضاء، وراجع نشاطهم، واحظر المسيئين.",
      partnersTitle: "الشركاء",
      partnersDescription: "راجع طلبات الرعاية وأدر ظهور الشركاء.",
      streamsTitle: "البث المصاحب",
      streamsDescription: "أدر قنوات البث المباشر على تويتش وكيك ويوتيوب وسوب.",
    },
    newsTitle: "الأخبار والمنشورات",
    newsDescription: "أنشئ وعدّل وانشر واحذف التحديثات المعروضة في صفحات الألعاب.",
  },
  newsList: {
    newPost: "منشور جديد",
    editPost: "تعديل المنشور",
    postsCount: (count: number) => `${count} منشور`,
    headers: {
      title: "العنوان",
      owner: "المالك",
      content: "المحتوى",
      status: "الحالة",
      updated: "آخر تحديث",
      actions: "الإجراءات",
    },
    mediaBadge: "إعلام",
    translatedContent: "إنجليزي + عربي",
    sharedContent: (locale: string) => `مشترك ${locale.toUpperCase()}`,
    published: "منشور",
    draft: "مسودة",
    empty: "لا توجد منشورات بعد. أنشئ أول تحديث للمجتمع.",
    deleteConfirm: "هل تريد حذف هذا المنشور؟ لا يمكن التراجع عن هذا الإجراء.",
    deleteTitle: "حذف هذا المنشور؟",
    deleteDescription:
      "سيتم حذف المنشور من لوحة الإدارة والصفحات العامة. لا يمكن التراجع عن هذا الإجراء.",
    deleteAction: "حذف المنشور",
    deleteSuccess: "تم حذف المنشور بنجاح.",
  },
  games: {
    title: "صفحات الألعاب",
    newTitle: "لعبة جديدة",
    editTitle: "تعديل اللعبة",
    description:
      "أضف أو عدّل أو رتّب أو احذف الألعاب المعروضة في الموقع العام. حذف لعبة سيحذف منشوراتها أيضا.",
    count: (count: number) => `${count} لعبة`,
    newAction: "لعبة جديدة",
    empty: "لا توجد ألعاب بعد. أضف أول لعبة.",
    deleteConfirm: (title: string) =>
      `هل تريد حذف "${title}"؟ سيؤدي ذلك أيضا إلى حذف منشوراتها ولا يمكن التراجع عنه.`,
    moveUp: "تحريك للأعلى",
    moveDown: "تحريك للأسفل",
  },
  media: {
    title: "قنوات الإعلام",
    newTitle: "قناة إعلام جديدة",
    editTitle: "تعديل قناة الإعلام",
    postsTitle: "المنشورات",
    descriptionSuper:
      "حسابات الإعلام الخاصة بالرياضات الإلكترونية المعروضة في الدليل العام. يمكنك إنشاء القنوات وتعديلها وترتيبها وحذفها.",
    descriptionScoped:
      "حسابات الإعلام الخاصة بالرياضات الإلكترونية المعروضة في الدليل العام. يمكنك تعديل القنوات المسندة لك.",
    channelPostsDescription:
      "المقالات المنشورة بواسطة هذه القناة. تظهر في صفحة القناة العامة وتنشر في قناة ديسكورد عند نشرها.",
    count: (count: number) => `${count} قناة`,
    linkCount: (count: number) => `${count} رابط`,
    newAction: "قناة جديدة",
    empty: "لا توجد قنوات إعلام بعد.",
    deleteConfirm: (name: string) => `هل تريد حذف "${name}"؟ لا يمكن التراجع عن هذا الإجراء.`,
    moveUp: "تحريك للأعلى",
    moveDown: "تحريك للأسفل",
  },
  comments: {
    title: "التعليقات",
    description: "راجع التعليقات المعلقة والتي تحتاج مراجعة. كل إجراء يتم تسجيله في سجل التدقيق.",
    filters: {
      pending: "معلقة",
      flagged: "تحتاج مراجعة",
      reported: "مُبلّغ عنها",
      visible: "ظاهرة",
      hidden: "مخفية",
      rejected: "مرفوضة",
      deleted: "محذوفة",
    },
    actions: {
      approve: "اعتماد",
      reject: "رفض",
      hide: "إخفاء",
      restore: "استعادة",
      delete: "حذف",
    },
    done: {
      approve: "تم اعتماد التعليق.",
      reject: "تم رفض التعليق.",
      hide: "تم إخفاء التعليق.",
      restore: "تمت استعادة التعليق.",
      delete: "تم حذف التعليق.",
      fallback: "تم تحديث التعليق.",
    },
    noComments: (filter: string) => `لا توجد تعليقات في "${filter}".`,
    authorFallback: "كاتب غير معروف",
    onPost: "على",
    postFallback: (id: number) => `منشور #${id}`,
    reply: "رد",
    profanity: "ألفاظ مسيئة",
    links: "روابط",
    reports: (n: number) => `${n} ${n === 1 ? "بلاغ" : "بلاغات"}`,
    deleteTitle: "حذف هذا التعليق؟",
    deleteDescription:
      "سيتم إزالة التعليق من النقاشات العامة مع الاحتفاظ بسجل المراجعة.",
  },
  users: {
    title: "المستخدمون",
    description: "الأعضاء الذين سجّلوا الدخول إلى اللوحة، الأحدث أولا. ابحث بالاسم أو بمعرف ديسكورد.",
    searchPlaceholder: "ابحث بالاسم أو بمعرف ديسكورد",
    searchAction: "بحث",
    headers: {
      member: "العضو",
      discordId: "معرف ديسكورد",
      joined: "تاريخ الانضمام",
      lastActive: "آخر نشاط",
      comments: "التعليقات",
      likes: "الإعجابات",
      ewcLinked: "مرتبط بـ EWC",
      status: "الحالة",
    },
    ewcLinkedBadge: "مرتبط بـ EWC",
    blockedBadge: "محظور",
    empty: "لا يوجد مستخدمون مطابقون.",
    previous: "السابق",
    next: "التالي",
    nameFallback: "عضو بدون اسم",
    detail: {
      activityTitle: "النشاط",
      comments: "التعليقات",
      likes: "الإعجابات",
      lastActive: "آخر نشاط",
      joined: "تاريخ الانضمام",
      never: "لا يوجد",
      commentsTitle: "تعليقاته",
      noComments: "لم يكتب هذا العضو أي تعليق بعد.",
    },
    block: {
      blockAction: "حظر العضو",
      unblockAction: "رفع الحظر",
      reasonPlaceholder: "السبب (اختياري)",
      blockedTitle: "محظور",
      blockedBy: "حظره",
      blockedReason: "السبب",
      confirmTitle: "حظر هذا العضو؟",
      confirmDescription:
        "لن يتمكن بعد الآن من التعليق أو الإعجاب. تبقى تعليقاته الحالية حتى تراجعها.",
      confirmAction: "حظر",
      blockedNotice: "تم حظر العضو.",
      unblockedNotice: "تم رفع الحظر عن العضو.",
    },
    moderation: {
      approve: "اعتماد",
      hide: "إخفاء",
      delete: "حذف",
      done: "تم تحديث التعليق.",
      deleteTitle: "حذف هذا التعليق؟",
      deleteDescription:
        "سيتم إزالة التعليق من النقاشات العامة مع الاحتفاظ بسجل المراجعة.",
    },
  },
  audit: {
    title: "سجل التدقيق",
    description: "آخر 100 تغيير في لوحة التحكم. هذا العرض للقراءة فقط، وسيتم إضافة التصفح لاحقا.",
    recentTitle: "النشاط الأخير",
    recentDescription: "كل عملية إدارة ناجحة تسجل هنا مع المستخدم والإجراء والهدف.",
    empty: "لا توجد سجلات تدقيق بعد.",
    headers: {
      time: "الوقت",
      actor: "المستخدم",
      action: "الإجراء",
      target: "الهدف",
    },
  },
  team: {
    title: "فريق الإدارة",
    description:
      "أضف الإداريين بمعرف ديسكورد وحدد الألعاب وقنوات الإعلام التي يمكن لكل شخص إدارتها. الإداريون العلويون يتم ضبطهم عبر متغير البيئة EWC_DASHBOARD_SUPER_ADMIN_DISCORD_IDS.",
    addCardTitle: "إضافة إداري",
    discordId: "معرف مستخدم ديسكورد",
    discordIdPlaceholder: "مثال: 100000000000000001",
    discordIdDescription: "معرف حساب العضو في ديسكورد.",
    displayName: "اسم العرض",
    displayNamePlaceholder: "مثال: فريق Echo MENA",
    gamesManage: "الألعاب التي يمكنه إدارتها",
    mediaManage: "قنوات الإعلام التي يمكنه إدارتها",
    games: "الألعاب",
    media: "قنوات الإعلام",
    addAction: "إضافة إداري",
    adminsCount: (count: number) => `الإداريون (${count})`,
    noneAvailable: "لا توجد خيارات متاحة",
    noName: "(بدون اسم)",
    noAssignments: "لا توجد صلاحيات محددة بعد",
    empty: "لا يوجد إداريون عاديون بعد. أضف إداريًا بالأعلى لتفويض ألعاب أو قنوات محددة.",
    discordIdRequired: "معرف ديسكورد مطلوب",
    addFailed: "فشلت إضافة الإداري",
    saveFailed: "فشل الحفظ",
    removeConfirm: (name: string) => `هل تريد إزالة ${name} من فريق الإدارة؟`,
  },
  streams: {
    addTitle: "إضافة قنوات بث مصاحب",
    addDescription:
      "أضف تويتش وكيك ويوتيوب وسوب لنفس صانع المحتوى من إجراء واحد، وحدد المنصة الافتراضية التي تظهر في التضمين.",
    couldNotSave: "تعذر الحفظ",
    platformError: (platform: string, status: number) => `تعذرت إضافة ${platform} (${status}).`,
    updateError: (label: string) => `تعذر تحديث ${label}.`,
    networkError: "حدث خطأ في الاتصال. حاول مرة أخرى.",
    validation: {
      platformRequired: "أضف اسم مستخدم أو رابط منصة واحدة على الأقل.",
      labelRequired: "اسم العرض مطلوب عند إضافة أكثر من منصة لنفس صانع المحتوى.",
      gameRequired: "اختر لعبة واحدة على الأقل لقناة مرتبطة بلعبة.",
    },
    labels: {
      streamer: "اسم صانع المحتوى",
      defaultPlatform: "منصة التضمين الافتراضية",
      platformPlaceholder: "المنصة الافتراضية",
      handleOrUrl: (platform: string) => `اسم مستخدم أو رابط ${platform}`,
      scope: "النطاق",
      language: "اللغة (اختياري)",
      team: "اسم الفريق",
      matchExternalId: "معرّف المباراة الخارجي",
      editLabel: "تعديل الاسم",
      editLanguage: "تعديل اللغة",
    },
    placeholders: {
      streamer: "OWBrain",
      twitch: "owbrain أو twitch.tv/owbrain",
      channelUrl: (platform: string) => `رابط قناة ${platform}`,
      language: "ar أو en",
      team: "Twisted Minds",
      matchExternalId: "sgg:104353062 أو Match:ID_...",
    },
    embedHelp: "التضمين متاح لتويتش وكيك وقنوات يوتيوب المباشرة. سوب يحفظ كرابط.",
    games: "الألعاب",
    gameTagsOptional: "وسوم الألعاب (اختياري)",
    selectedCount: (count: number) =>
      count === 0
        ? "لا توجد ألعاب محددة"
        : count === 1
          ? "لعبة واحدة محددة"
          : count === 2
            ? "لعبتان محددتان"
            : count <= 10
              ? `${count} ألعاب محددة`
              : `${count} لعبة محددة`,
    gamePickerHelp:
      "اختر الألعاب بالأزرار بدل كتابة الفواصل. يمكن لصانع المحتوى الظهور تحت أكثر من لعبة.",
    scopeLabels: {
      ewc: "قائمة EWC الرسمية",
      game: "حسب اللعبة",
      team: "حسب الفريق",
      match: "حسب المباراة",
    },
    addAction: "إضافة صانع محتوى",
    channelsCount: (count: number) =>
      count === 0
        ? "لا توجد قنوات"
        : count === 1
          ? "قناة واحدة"
          : count === 2
            ? "قناتان"
            : count <= 10
              ? `${count} قنوات`
              : `${count} قناة`,
    streamersCount: (count: number) =>
      count === 0
        ? "لا يوجد صناع محتوى"
        : count === 1
          ? "صانع محتوى واحد"
          : count === 2
            ? "صانعا محتوى"
            : count <= 10
              ? `${count} صناع محتوى`
              : `${count} صانع محتوى`,
    platformsCount: (count: number) =>
      count === 1 ? "منصة واحدة" : count === 2 ? "منصتان" : `${count} منصات`,
    inactive: "غير مفعلة",
    group: (key: string) => `المجموعة: ${key}`,
    defaultBadge: "الافتراضية",
    setDefault: "اجعلها الافتراضية",
    disable: "تعطيل",
    enable: "تفعيل",
    save: "حفظ",
    cancel: "إلغاء",
    remove: "إزالة",
    removeStreamer: "إزالة صانع المحتوى",
    empty: "لا توجد قنوات بعد.",
    removeTitle: "إزالة قناة البث المصاحب؟",
    removeDescription: (platform: string, handle: string) =>
      `سيتم حذف ${platform} / ${handle} من سجل قنوات البث المصاحب.`,
    removeStreamerTitle: "إزالة صانع المحتوى؟",
    removeStreamerDescription: (label: string, count: number) =>
      `سيتم حذف جميع قنوات ${label} (${count === 1 ? "قناة واحدة" : count === 2 ? "قناتان" : `${count} قنوات`}) من هذا النطاق.`,
  },
  editor: {
    titleLabel: "العنوان",
    nameLabel: "الاسم",
    descriptionLabel: "الوصف",
    ownerLabel: "المالك",
    englishPlaceholder: "الإنجليزية",
    arabicPlaceholder: "العربية",
    urlSlug: "مسار الرابط",
    fixedSlug: "المسار ثابت بعد الإنشاء.",
    fixedGameSlug: "المسار ثابت بعد الإنشاء لأنه جزء من الرابط العام.",
    gamePublicUrl: (slug: string) => `الرابط العام: /games/${slug || "your-slug"}`,
    mediaPublicUrl: (slug: string) => `الرابط العام: /media/${slug || "your-slug"}`,
    titleDescription: "يظهر كاسم اللعبة، وهو مطلوب باللغتين.",
    statusBadge: "شارة الحالة",
    statusDescription: 'الشارة الصغيرة، مثل "التغطية جاهزة".',
    discordNewsChannel: "معرف قناة أخبار ديسكورد",
    discordNewsDescription:
      "اختياري. الأخبار المنشورة لهذه اللعبة ترسل تلقائيا هنا. اتركه فارغا لاستخدام قناة الأخبار الافتراضية في السيرفر.",
    focusTags: "وسوم التركيز",
    englishTag: "وسم بالإنجليزية",
    arabicTag: "وسم بالعربية",
    removeTag: "حذف الوسم",
    addTag: "إضافة وسم",
    focusDescription: "مواضيع قصيرة تظهر في صفحة اللعبة.",
    createGame: "إنشاء اللعبة",
    logoImage: "صورة الشعار (اختياري)",
    upload: "رفع",
    uploadFailed: "فشل الرفع",
    socialLinks: "روابط المنصات",
    removeLink: "حذف الرابط",
    addLink: "إضافة رابط",
    linksDescription: "يتم حفظ روابط http(s) فقط.",
    discordChannelOptional: "معرف قناة ديسكورد (اختياري)",
    invalidDiscordChannel: "أدخل معرف قناة ديسكورد صحيحا (17-20 رقما).",
    mediaDiscordDescription:
      "اضبط هذا الخيار لنشر القناة تلقائيا في ديسكورد عند الإنشاء أو التعديل. اتركه فارغا لإيقاف النشر في ديسكورد.",
    createChannel: "إنشاء القناة",
  },
};

export type AdminCopy = typeof en;

export function getAdminCopy(locale: Locale): AdminCopy {
  return locale === "ar" ? ar : en;
}
