import type { Locale } from "@/lib/i18n";

const ADMIN_MCP_COPY_PAGE_EN = [
  "# Admin MCP",
  "",
  "The admin MCP endpoint lets approved AI/admin clients read site state and run small, audited admin actions without sharing dashboard sessions or database credentials.",
  "",
  "This documentation page is public so AI assistants can read it. The MCP endpoint itself remains admin-only and requires a valid scoped bearer key.",
  "",
  "Public docs page:",
  "",
  "```text",
  "https://esportscommunity.net/docs/admin-mcp",
  "```",
  "",
  "## Endpoint",
  "",
  "Production:",
  "",
  "```text",
  "https://esportscommunity.net/api/mcp",
  "```",
  "",
  "Local development:",
  "",
  "```text",
  "http://localhost:3000/api/mcp",
  "```",
  "",
  "Required headers:",
  "",
  "```http",
  "Authorization: Bearer <ec_mcp_live_...>",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "JSON-RPC batch arrays are intentionally rejected. Send one MCP request at a time.",
  "",
  "## Create A Key",
  "",
  "1. Sign in to the dashboard with your admin account.",
  "2. Open /admin/mcp.",
  "3. Create a key for your signed-in Discord account.",
  "4. Choose tools and the smallest useful game/media scopes.",
  "5. Copy the generated ec_mcp_live_... key immediately.",
  "",
  "The full key is shown once. The database stores only a SHA-256 hash, short prefix, your owner metadata, scopes, timestamps, and revocation state. Scoped admins can only create and revoke their own keys; super admins can view and revoke all keys.",
  "",
  "## Tools",
  "",
  "Admin MCP includes all public read-only tools, so admins do not need to configure the public MCP separately.",
  "",
  "- get_site_overview: read site/bot counts. Super keys also see extra admin context.",
  "- list_games: localized public game directory.",
  "- search_news: search admin-visible news posts within scope.",
  "- get_tournament_status: read one tournament's matches and standings within scope.",
  "- list_tournaments: list public active tournament summaries.",
  "- get_ewc_club_summary: read EWC club points, qualified games, wins, and region metadata.",
  "- list_co_streams: list public co-stream groups, live-first.",
  "- search_teams: public team directory search with safe public fields.",
  "- search_players: public player directory search with safe public fields.",
  "- get_public_ewc_leaderboard: existing public prediction leaderboard projection.",
  "- list_admin_queue: list reported comments needing moderation review.",
  "- create_news_draft: create a draft news post only. It never publishes directly.",
  "- update_stream_channel: update allowed co-stream rows.",
  "",
  "Every successful write records an admin audit entry with actor id mcp:<key-id>:<owner-discord-id>.",
  "",
  "## Client Setup",
  "",
  "Use native Streamable HTTP MCP configuration when your client supports it.",
  "",
  "For stdio-only clients such as some Claude Code, Cursor, VS Code, or Codex setups, use mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community-admin": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/mcp",',
  '        "--header",',
  '        "Authorization: Bearer <MCP_KEY>"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "For Codex config.toml stdio setup:",
  "",
  "```toml",
  "[mcp_servers.esports-community-admin]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/mcp",',
  '  "--header",',
  '  "Authorization: Bearer <MCP_KEY>",',
  "]",
  "```",
  "",
  "For Codex versions with native Streamable HTTP support, keep the raw key in an environment variable and reference the variable name:",
  "",
  "```toml",
  "[mcp_servers.esports_community]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/mcp"',
  'bearer_token_env_var = "ESPORTS_COMMUNITY_MCP_TOKEN"',
  "```",
  "",
  "`ESPORTS_COMMUNITY_MCP_TOKEN` should contain the raw `ec_mcp_live_...` key, without `Bearer `.",
  "",
  "Restart the MCP client after changing configuration.",
  "",
  "## Security Notes",
  "",
  "- Admins can create MCP keys only for their own signed-in account.",
  "- Scoped admins can only select scopes already assigned to them.",
  "- Super admins can view and revoke all MCP keys.",
  "- Scope keys to the smallest useful tool/game/media set.",
  "- Treat MCP keys like admin credentials.",
  "- Do not paste real keys into screenshots, commits, issue comments, or shared prompts.",
  "- Revoke old keys after rotation.",
].join("\n");

const ADMIN_MCP_COPY_PAGE_AR = [
  "# خادم MCP الإداري",
  "",
  "تتيح نقطة نهاية MCP الإدارية للعملاء المعتمدين من أدوات الذكاء الاصطناعي أو الإدارة قراءة حالة الموقع وتنفيذ إجراءات إدارية صغيرة ومدققة بدون مشاركة جلسات لوحة التحكم أو بيانات قاعدة البيانات.",
  "",
  "هذه الصفحة عامة حتى تتمكن أدوات الذكاء الاصطناعي من قراءة شرح الإعداد. نقطة نهاية MCP نفسها تبقى مخصصة للمسؤولين فقط وتتطلب مفتاح Bearer صالح ومحدد الصلاحيات.",
  "",
  "صفحة الشرح العامة:",
  "",
  "```text",
  "https://esportscommunity.net/docs/admin-mcp",
  "```",
  "",
  "## نقطة النهاية",
  "",
  "الإنتاج:",
  "",
  "```text",
  "https://esportscommunity.net/api/mcp",
  "```",
  "",
  "التطوير المحلي:",
  "",
  "```text",
  "http://localhost:3000/api/mcp",
  "```",
  "",
  "الترويسات المطلوبة:",
  "",
  "```http",
  "Authorization: Bearer <ec_mcp_live_...>",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "يتم رفض مصفوفات JSON-RPC batch عمدا. أرسل طلب MCP واحدا في كل مرة.",
  "",
  "## إنشاء مفتاح",
  "",
  "1. سجل الدخول إلى لوحة التحكم بحسابك الإداري.",
  "2. افتح /admin/mcp.",
  "3. أنشئ مفتاحا لحساب ديسكورد المسجل حاليا.",
  "4. اختر الأدوات وأصغر نطاق مفيد من الألعاب أو المنصات الإعلامية.",
  "5. انسخ مفتاح ec_mcp_live_... الذي يتم إنشاؤه فورا.",
  "",
  "يظهر المفتاح الكامل مرة واحدة فقط. قاعدة البيانات تحفظ فقط SHA-256 hash، وبادئة قصيرة، وبيانات المالك، والنطاقات، والطوابع الزمنية، وحالة الإلغاء. يستطيع المسؤولون محدودو النطاق إنشاء وإلغاء مفاتيحهم فقط، بينما يستطيع المسؤولون الأعلى عرض وإلغاء كل المفاتيح.",
  "",
  "## الأدوات",
  "",
  "يتضمن MCP الإداري كل أدوات القراءة العامة، لذلك لا يحتاج المسؤولون إلى إضافة MCP العام بشكل منفصل.",
  "",
  "- قراءة أعداد الموقع والبوت. مفاتيح المسؤول الأعلى ترى أيضا سياقا إداريا إضافيا: `get_site_overview`.",
  "- دليل الألعاب العام حسب اللغة: `list_games`.",
  "- البحث في الأخبار الظاهرة للمسؤول ضمن نطاق صلاحيات المفتاح: `search_news`.",
  "- قراءة مباريات وترتيب بطولة واحدة ضمن النطاق المسموح: `get_tournament_status`.",
  "- عرض ملخصات البطولات النشطة العامة: `list_tournaments`.",
  "- قراءة نقاط أندية EWC، والألعاب المتأهلة، والانتصارات، وبيانات المنطقة: `get_ewc_club_summary`.",
  "- عرض مجموعات البث المشترك العامة مع إظهار المباشر أولا: `list_co_streams`.",
  "- البحث في دليل الفرق العام بحقول عامة آمنة: `search_teams`.",
  "- البحث في دليل اللاعبين العام بحقول عامة آمنة: `search_players`.",
  "- عرض لوحة توقعات EWC العامة الحالية: `get_public_ewc_leaderboard`.",
  "- عرض التعليقات المبلغ عنها التي تحتاج مراجعة: `list_admin_queue`.",
  "- إنشاء مسودة خبر فقط. لا ينشر مباشرة أبدا: `create_news_draft`.",
  "- تحديث صفوف البث المشترك المسموح بها: `update_stream_channel`.",
  "",
  "كل عملية كتابة ناجحة تسجل إدخالا في سجل تدقيق الإدارة باستخدام actor id بالشكل mcp:<key-id>:<owner-discord-id>.",
  "",
  "## إعداد العميل",
  "",
  "استخدم إعداد Streamable HTTP MCP الأصلي عندما يدعمه العميل.",
  "",
  "للعملاء الذين يدعمون stdio فقط، مثل بعض إعدادات Claude Code أو Cursor أو VS Code أو Codex، استخدم mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community-admin": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/mcp",',
  '        "--header",',
  '        "Authorization: Bearer <MCP_KEY>"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "لإعداد Codex عبر config.toml باستخدام stdio:",
  "",
  "```toml",
  "[mcp_servers.esports-community-admin]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/mcp",',
  '  "--header",',
  '  "Authorization: Bearer <MCP_KEY>",',
  "]",
  "```",
  "",
  "لإصدارات Codex التي تدعم Streamable HTTP بشكل مباشر، ضع المفتاح الخام في متغير بيئة ثم أشر إلى اسم المتغير:",
  "",
  "```toml",
  "[mcp_servers.esports_community]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/mcp"',
  'bearer_token_env_var = "ESPORTS_COMMUNITY_MCP_TOKEN"',
  "```",
  "",
  "يجب أن يحتوي ESPORTS_COMMUNITY_MCP_TOKEN على مفتاح ec_mcp_live_... الخام، بدون Bearer.",
  "",
  "أعد تشغيل عميل MCP بعد تغيير الإعدادات.",
  "",
  "## ملاحظات الأمان",
  "",
  "- يستطيع المسؤولون إنشاء مفاتيح MCP لحسابهم المسجل فقط.",
  "- يستطيع المسؤولون محدودو النطاق اختيار النطاقات المخصصة لهم فقط.",
  "- يستطيع المسؤولون الأعلى عرض وإلغاء كل مفاتيح MCP.",
  "- اجعل نطاق المفتاح على أصغر مجموعة أدوات أو ألعاب أو منصات مفيدة.",
  "- تعامل مع مفاتيح MCP مثل بيانات اعتماد الإدارة.",
  "- لا تلصق المفاتيح الحقيقية في لقطات الشاشة أو commits أو تعليقات issues أو prompts مشتركة.",
  "- ألغ المفاتيح القديمة بعد تدويرها.",
].join("\n");

export const ADMIN_MCP_COPY_PAGE_BY_LOCALE: Record<Locale, string> = {
  en: ADMIN_MCP_COPY_PAGE_EN,
  ar: ADMIN_MCP_COPY_PAGE_AR,
};

export const ADMIN_MCP_COPY_PAGE = ADMIN_MCP_COPY_PAGE_EN;

export function getAdminMcpCopyPage(locale: Locale) {
  return ADMIN_MCP_COPY_PAGE_BY_LOCALE[locale];
}
