import { MCP_TOOL_MANIFEST } from "@/lib/mcp-tool-manifest";
import type { Locale } from "@/lib/i18n";

const ADMIN_GRANT_LABELS: Record<Locale, Record<"always" | "selectable", string>> = {
  en: {
    always: "always-on",
    selectable: "key-selected",
  },
  ar: {
    always: "متاحة دائما",
    selectable: "تتطلب اختيارها في المفتاح",
  },
};

function adminMcpToolLines(locale: Locale) {
  return MCP_TOOL_MANIFEST
    .filter((tool) => tool.surfaces.includes("admin"))
    .map((tool) => `- \`${tool.name}\` (${ADMIN_GRANT_LABELS[locale][tool.adminGrant]}): ${tool.description[locale]}`);
}

const ADMIN_MCP_COPY_PAGE_EN = [
  "# Admin MCP",
  "",
  "The admin MCP endpoint lets approved AI/admin clients read site state and run small, audited admin actions without sharing dashboard sessions or database credentials.",
  "",
  "This documentation page is public so AI assistants can read it. The MCP endpoint itself remains admin-only and requires a valid scoped bearer key.",
  "",
  "Public docs page:",
  "",
  "```text",
  "https://esportscommunity.net/docs/admin-mcp",
  "```",
  "",
  "## Endpoint",
  "",
  "Production:",
  "",
  "```text",
  "https://esportscommunity.net/api/mcp",
  "```",
  "",
  "Local development:",
  "",
  "```text",
  "http://localhost:3000/api/mcp",
  "```",
  "",
  "Required headers:",
  "",
  "```http",
  "Authorization: Bearer <ec_mcp_live_...>",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "JSON-RPC batch arrays are intentionally rejected. Send one MCP request at a time.",
  "",
  "## Create A Key",
  "",
  "1. Sign in to the dashboard with your admin account.",
  "2. Open /admin/mcp.",
  "3. Create a key for your signed-in Discord account.",
  "4. Choose tools and the smallest useful game/media scopes.",
  "5. Copy the generated ec_mcp_live_... key immediately.",
  "",
  "The full key is shown once. The database stores only a SHA-256 hash, short prefix, your owner metadata, scopes, timestamps, and revocation state. Scoped admins can only create and revoke their own keys; super admins can view and revoke all keys.",
  "",
  "## Tools",
  "",
  "Admin MCP includes all public read-only tools, so admins do not need to configure the public MCP separately.",
  "Always-on tools are available to every valid admin MCP key. Key-selected tools require an explicit grant on the key.",
  "",
  ...adminMcpToolLines("en"),
  "",
  "Every successful write records an admin audit entry with actor id mcp:<key-id>:<owner-discord-id>.",
  "",
  "## Workflow Example",
  "",
  "1. Call `get_admin_capabilities`.",
  "2. Pick an allowed game slug, media slug, or stream channel id from the response.",
  "3. Call `create_news_draft` or `update_stream_channel` with that allowed resource.",
  "4. For every write, include a caller-generated `idempotencyKey` and reuse it only when retrying the exact same operation.",
  "",
  "Example write arguments:",
  "",
  "```json",
  "{",
  '  "idempotencyKey": "018f7b3d-atomic-draft-001",',
  '  "title": "Draft title",',
  '  "gameSlug": "valorant"',
  "}",
  "```",
  "",
  "## Client Setup",
  "",
  "Use native Streamable HTTP MCP configuration when your client supports it.",
  "",
  "For stdio-only clients such as some Claude Code, Cursor, VS Code, or Codex setups, use mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community-admin": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/mcp",',
  '        "--header",',
  '        "Authorization: Bearer <MCP_KEY>"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "For Codex config.toml stdio setup:",
  "",
  "```toml",
  "[mcp_servers.esports-community-admin]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/mcp",',
  '  "--header",',
  '  "Authorization: Bearer <MCP_KEY>",',
  "]",
  "```",
  "",
  "For Codex versions with native Streamable HTTP support, keep the raw key in an environment variable and reference the variable name:",
  "",
  "```toml",
  "[mcp_servers.esports_community]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/mcp"',
  'bearer_token_env_var = "ESPORTS_COMMUNITY_MCP_TOKEN"',
  "```",
  "",
  "`ESPORTS_COMMUNITY_MCP_TOKEN` should contain the raw `ec_mcp_live_...` key, without `Bearer `.",
  "",
  "Restart the MCP client after changing configuration.",
  "",
  "## Security Notes",
  "",
  "- Admins can create MCP keys only for their own signed-in account.",
  "- Scoped admins can only select scopes already assigned to them.",
  "- Super admins can view and revoke all MCP keys.",
  "- Scope keys to the smallest useful tool/game/media set.",
  "- Treat MCP keys like admin credentials.",
  "- Do not paste real keys into screenshots, commits, issue comments, or shared prompts.",
  "- Revoke old keys after rotation.",
].join("\n");

const ADMIN_MCP_COPY_PAGE_AR = [
  "# خادم MCP الإداري",
  "",
  "تتيح نقطة نهاية MCP الإدارية للعملاء المعتمدين من أدوات الذكاء الاصطناعي أو الإدارة قراءة حالة الموقع وتنفيذ إجراءات إدارية صغيرة ومدققة بدون مشاركة جلسات لوحة التحكم أو بيانات قاعدة البيانات.",
  "",
  "هذه الصفحة عامة حتى تتمكن أدوات الذكاء الاصطناعي من قراءة شرح الإعداد. نقطة نهاية MCP نفسها تبقى مخصصة للمسؤولين فقط وتتطلب مفتاح Bearer صالح ومحدد الصلاحيات.",
  "",
  "صفحة الشرح العامة:",
  "",
  "```text",
  "https://esportscommunity.net/docs/admin-mcp",
  "```",
  "",
  "## نقطة النهاية",
  "",
  "الإنتاج:",
  "",
  "```text",
  "https://esportscommunity.net/api/mcp",
  "```",
  "",
  "التطوير المحلي:",
  "",
  "```text",
  "http://localhost:3000/api/mcp",
  "```",
  "",
  "الترويسات المطلوبة:",
  "",
  "```http",
  "Authorization: Bearer <ec_mcp_live_...>",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "يتم رفض مصفوفات JSON-RPC batch عمدا. أرسل طلب MCP واحدا في كل مرة.",
  "",
  "## إنشاء مفتاح",
  "",
  "1. سجل الدخول إلى لوحة التحكم بحسابك الإداري.",
  "2. افتح /admin/mcp.",
  "3. أنشئ مفتاحا لحساب ديسكورد المسجل حاليا.",
  "4. اختر الأدوات وأصغر نطاق مفيد من الألعاب أو المنصات الإعلامية.",
  "5. انسخ مفتاح ec_mcp_live_... الذي يتم إنشاؤه فورا.",
  "",
  "يظهر المفتاح الكامل مرة واحدة فقط. قاعدة البيانات تحفظ فقط SHA-256 hash، وبادئة قصيرة، وبيانات المالك، والنطاقات، والطوابع الزمنية، وحالة الإلغاء. يستطيع المسؤولون محدودو النطاق إنشاء وإلغاء مفاتيحهم فقط، بينما يستطيع المسؤولون الأعلى عرض وإلغاء كل المفاتيح.",
  "",
  "## الأدوات",
  "",
  "يتضمن MCP الإداري كل أدوات القراءة العامة، لذلك لا يحتاج المسؤولون إلى إضافة MCP العام بشكل منفصل.",
  "الأدوات المتاحة دائما تعمل مع أي مفتاح MCP إداري صالح. الأدوات التي تتطلب اختيارها تحتاج إلى منح صريح في المفتاح.",
  "",
  ...adminMcpToolLines("ar"),
  "",
  "كل عملية كتابة ناجحة تسجل إدخالا في سجل تدقيق الإدارة باستخدام actor id بالشكل mcp:<key-id>:<owner-discord-id>.",
  "",
  "## مثال سير عمل",
  "",
  "1. استدع `get_admin_capabilities`.",
  "2. اختر slug لعبة أو قناة إعلامية أو id قناة بث مسموحا به من الاستجابة.",
  "3. استدع `create_news_draft` أو `update_stream_channel` باستخدام المورد المسموح.",
  "",
  "## إعداد العميل",
  "",
  "استخدم إعداد Streamable HTTP MCP الأصلي عندما يدعمه العميل.",
  "",
  "للعملاء الذين يدعمون stdio فقط، مثل بعض إعدادات Claude Code أو Cursor أو VS Code أو Codex، استخدم mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community-admin": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/mcp",',
  '        "--header",',
  '        "Authorization: Bearer <MCP_KEY>"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "لإعداد Codex عبر config.toml باستخدام stdio:",
  "",
  "```toml",
  "[mcp_servers.esports-community-admin]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/mcp",',
  '  "--header",',
  '  "Authorization: Bearer <MCP_KEY>",',
  "]",
  "```",
  "",
  "لإصدارات Codex التي تدعم Streamable HTTP بشكل مباشر، ضع المفتاح الخام في متغير بيئة ثم أشر إلى اسم المتغير:",
  "",
  "```toml",
  "[mcp_servers.esports_community]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/mcp"',
  'bearer_token_env_var = "ESPORTS_COMMUNITY_MCP_TOKEN"',
  "```",
  "",
  "يجب أن يحتوي ESPORTS_COMMUNITY_MCP_TOKEN على مفتاح ec_mcp_live_... الخام، بدون Bearer.",
  "",
  "أعد تشغيل عميل MCP بعد تغيير الإعدادات.",
  "",
  "## ملاحظات الأمان",
  "",
  "- يستطيع المسؤولون إنشاء مفاتيح MCP لحسابهم المسجل فقط.",
  "- يستطيع المسؤولون محدودو النطاق اختيار النطاقات المخصصة لهم فقط.",
  "- يستطيع المسؤولون الأعلى عرض وإلغاء كل مفاتيح MCP.",
  "- اجعل نطاق المفتاح على أصغر مجموعة أدوات أو ألعاب أو منصات مفيدة.",
  "- تعامل مع مفاتيح MCP مثل بيانات اعتماد الإدارة.",
  "- لا تلصق المفاتيح الحقيقية في لقطات الشاشة أو commits أو تعليقات issues أو prompts مشتركة.",
  "- ألغ المفاتيح القديمة بعد تدويرها.",
].join("\n");

export const ADMIN_MCP_COPY_PAGE_BY_LOCALE: Record<Locale, string> = {
  en: ADMIN_MCP_COPY_PAGE_EN,
  ar: ADMIN_MCP_COPY_PAGE_AR,
};

export const ADMIN_MCP_COPY_PAGE = ADMIN_MCP_COPY_PAGE_EN;

export function getAdminMcpCopyPage(locale: Locale) {
  return ADMIN_MCP_COPY_PAGE_BY_LOCALE[locale];
}
