export const ADMIN_MCP_COPY_PAGE = [
  "# Admin MCP",
  "",
  "The admin MCP endpoint lets approved AI/admin clients read site state and run small, audited admin actions without sharing dashboard sessions or database credentials.",
  "",
  "This documentation page is public so AI assistants can read it. The MCP endpoint itself remains admin-only and requires a valid scoped bearer key.",
  "",
  "Public docs page:",
  "",
  "```text",
  "https://esportscommunity.net/mcp",
  "```",
  "",
  "## Endpoint",
  "",
  "Production:",
  "",
  "```text",
  "https://esportscommunity.net/api/mcp",
  "```",
  "",
  "Local development:",
  "",
  "```text",
  "http://localhost:3000/api/mcp",
  "```",
  "",
  "Required headers:",
  "",
  "```http",
  "Authorization: Bearer <ec_mcp_live_...>",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "JSON-RPC batch arrays are intentionally rejected. Send one MCP request at a time.",
  "",
  "## Create A Key",
  "",
  "1. Sign in to the dashboard as a super admin.",
  "2. Open /admin/mcp.",
  "3. Create a key for an existing dashboard admin or super admin Discord ID.",
  "4. Choose tools and optional game/media scopes.",
  "5. Copy the generated ec_mcp_live_... key immediately.",
  "",
  "The full key is shown once. The database stores only a SHA-256 hash, short prefix, owner metadata, scopes, timestamps, and revocation state.",
  "",
  "## Tools",
  "",
  "- get_site_overview: read site/bot counts. Super keys also see recent audit rows.",
  "- search_news: search admin-visible news posts within scope.",
  "- get_tournament_status: read one tournament's matches and standings within scope.",
  "- get_ewc_club_summary: read EWC club points, qualified games, wins, and region metadata.",
  "- list_admin_queue: list reported comments needing moderation review.",
  "- create_news_draft: create a draft news post only. It never publishes directly.",
  "- update_stream_channel: update allowed co-stream rows.",
  "",
  "Every successful write records an admin audit entry with actor id mcp:<key-id>:<owner-discord-id>.",
  "",
  "## Client Setup",
  "",
  "Use native Streamable HTTP MCP configuration when your client supports it.",
  "",
  "For stdio-only clients such as some Claude Code, Cursor, VS Code, or Codex setups, use mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community-admin": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/mcp",',
  '        "--header",',
  '        "Authorization: Bearer <MCP_KEY>"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "For Codex config.toml stdio setup:",
  "",
  "```toml",
  "[mcp_servers.esports-community-admin]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/mcp",',
  '  "--header",',
  '  "Authorization: Bearer <MCP_KEY>",',
  "]",
  "```",
  "",
  "For Codex versions with native Streamable HTTP support, keep the raw key in an environment variable and reference the variable name:",
  "",
  "```toml",
  "[mcp_servers.esports_community]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/mcp"',
  'bearer_token_env_var = "ESPORTS_COMMUNITY_MCP_TOKEN"',
  "```",
  "",
  "`ESPORTS_COMMUNITY_MCP_TOKEN` should contain the raw `ec_mcp_live_...` key, without `Bearer `.",
  "",
  "Restart the MCP client after changing configuration.",
  "",
  "## Security Notes",
  "",
  "- Only super admins can create or revoke MCP keys.",
  "- Scope keys to the smallest useful tool/game/media set.",
  "- Treat MCP keys like admin credentials.",
  "- Do not paste real keys into screenshots, commits, issue comments, or shared prompts.",
  "- Revoke old keys after rotation.",
  "",
  "Full repo guide: docs/ADMIN_MCP.md",
].join("\n");
