import { MCP_TOOL_MANIFEST } from "@/lib/mcp-tool-manifest";
import type { Locale } from "@/lib/i18n";

function publicMcpToolLines(locale: Locale) {
  return MCP_TOOL_MANIFEST
    .filter((tool) => tool.surfaces.includes("public"))
    .map((tool) => `- \`${tool.name}\`: ${tool.description[locale]}`);
}

const PUBLIC_MCP_COPY_PAGE_EN = [
  "# Public MCP",
  "",
  "The public MCP endpoint lets AI assistants read the same public Esports Community data that appears on the website. No key is required.",
  "",
  "It is read-only and returns public website data intended for visitors.",
  "",
  "Docs page:",
  "",
  "```text",
  "https://esportscommunity.net/docs/mcp",
  "```",
  "",
  "## Endpoint",
  "",
  "Production:",
  "",
  "```text",
  "https://esportscommunity.net/api/public-mcp",
  "```",
  "",
  "Local development:",
  "",
  "```text",
  "http://localhost:3000/api/public-mcp",
  "```",
  "",
  "Headers required by both revisions:",
  "",
  "```http",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "No bearer key is required. JSON-RPC batch arrays are rejected; send one MCP request at a time.",
  "",
  "## Protocol Revisions",
  "",
  "Both MCP eras are served on the same URL. The endpoint answers whichever one the request declares, so neither needs a separate address.",
  "",
  "- Revision `2026-07-28` — stateless. No `initialize` handshake and no session id.",
  "- Revisions `2025-11-25` and earlier — the `initialize` handshake, unchanged. This is still what most clients speak, so the setup below needs no changes.",
  "",
  "> **Deprecated — removal on 2026-11-23.** The `initialize` handshake era is deprecated as of 2026-08-12 and will stop being served on **2026-11-23**. Nothing changes before that date: handshake clients keep working exactly as they do now. Point your client at `2026-07-28` any time before then. After removal, a handshake request is answered with the unsupported-protocol-version error naming what the endpoint still serves.",
  "",
  "`server/discover` reports only `2026-07-28`. That is the modern revision it can negotiate, not the full list of what the endpoint serves — legacy clients never call it, they open with `initialize`.",
  "",
  "A 2026-07-28 request mirrors three body values into headers and repeats the protocol version inside `params._meta`:",
  "",
  "```http",
  "POST /api/public-mcp HTTP/1.1",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "MCP-Protocol-Version: 2026-07-28",
  "Mcp-Method: tools/call",
  "Mcp-Name: list_games",
  "",
  "{",
  '  "jsonrpc": "2.0",',
  '  "id": 1,',
  '  "method": "tools/call",',
  '  "params": {',
  '    "name": "list_games",',
  '    "arguments": { "locale": "en" },',
  '    "_meta": {',
  '      "io.modelcontextprotocol/protocolVersion": "2026-07-28",',
  '      "io.modelcontextprotocol/clientInfo": { "name": "YourClient", "version": "1.0.0" },',
  '      "io.modelcontextprotocol/clientCapabilities": {}',
  "    }",
  "  }",
  "}",
  "```",
  "",
  "`Mcp-Name` is required for `tools/call` only, and must match `params.name`. A header that disagrees with the body is rejected with JSON-RPC error `-32020`; an unsupported protocol version with `-32022`, which names what this endpoint does support.",
  "",
  "Every 2026-07-28 result carries `resultType: \"complete\"`. `tools/list` and `server/discover` also carry `ttlMs` and `cacheScope`: this endpoint returns the same tools to every caller, so its list is `cacheScope: \"public\"` and shared caches may hold it.",
  "",
  "## Tools",
  "",
  ...publicMcpToolLines("en"),
  "",
  "## Example questions",
  "",
  '- "Show the latest Valorant EWC news and include website links."',
  '- "Which clubs lead the EWC Club Championship standings?"',
  '- "Show the community EWC prediction leaderboard."',
  '- "Find Team Falcons and list its public profile details."',
  "",
  "Club Championship standings and community prediction rankings are separate datasets and use separate tools.",
  "",
  "## Client Setup",
  "",
  "Use native Streamable HTTP MCP configuration when your client supports it.",
  "",
  "For stdio-only clients, use mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/public-mcp"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "For Codex config.toml stdio setup:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/public-mcp",',
  "]",
  "```",
  "",
  "For clients with native Streamable HTTP support:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/public-mcp"',
  "```",
  "",
  "Restart the MCP client after changing configuration.",
  "",
  "## Security Notes",
  "",
  "- This endpoint is public and read-only.",
  "- Browser-origin requests are origin-checked.",
  "- Requests are rate-limited by trusted edge IP. If no trusted IP header is present, requests share one fallback bucket.",
  "- Responses are limited to public website fields.",
].join("\n");

const PUBLIC_MCP_COPY_PAGE_AR = [
  "# خادم MCP العام",
  "",
  "نقطة نهاية MCP العامة تتيح لأدوات الذكاء الاصطناعي قراءة نفس بيانات Esports Community العامة الظاهرة في الموقع. لا تحتاج إلى مفتاح.",
  "",
  "هذه النقطة للقراءة فقط وتعرض بيانات عامة مخصصة لزوار الموقع.",
  "",
  "صفحة الشرح:",
  "",
  "```text",
  "https://esportscommunity.net/ar/docs/mcp",
  "```",
  "",
  "## نقطة النهاية",
  "",
  "الإنتاج:",
  "",
  "```text",
  "https://esportscommunity.net/api/public-mcp",
  "```",
  "",
  "التطوير المحلي:",
  "",
  "```text",
  "http://localhost:3000/api/public-mcp",
  "```",
  "",
  "الترويسات المطلوبة في كلا الإصدارين:",
  "",
  "```http",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "لا تحتاج إلى مفتاح Bearer. يتم رفض طلبات JSON-RPC batch؛ أرسل طلب MCP واحدا في كل مرة.",
  "",
  "## إصدارات البروتوكول",
  "",
  "يخدم العنوان نفسه كلا إصداري MCP، ويجيب حسب ما يعلنه الطلب، فلا يحتاج أي منهما إلى عنوان منفصل.",
  "",
  "- الإصدار `2026-07-28` — بدون حالة. لا توجد مصافحة `initialize` ولا معرف جلسة.",
  "- الإصدارات `2025-11-25` وما قبلها — عبر مصافحة `initialize` دون تغيير، وهي ما تستخدمه معظم العملاء حتى الآن، فلا يحتاج الإعداد أدناه إلى أي تعديل.",
  "",
  "> **إيقاف مُعلن — الإزالة في 2026-11-23.** أصبحت مصافحة `initialize` مهجورة اعتبارا من 2026-08-12 وسيتوقف تقديمها في **2026-11-23**. لا شيء يتغير قبل هذا التاريخ: العملاء الذين يستخدمون المصافحة يعملون كما هم تماما. انقل عميلك إلى `2026-07-28` في أي وقت قبل ذلك. وبعد الإزالة يُجاب طلب المصافحة بخطأ الإصدار غير المدعوم مع ذكر ما تبقى مدعوما.",
  "",
  "يعيد `server/discover` الإصدار `2026-07-28` فقط، وهو الإصدار الحديث القابل للتفاوض وليس قائمة كل ما تخدمه النقطة؛ فالعملاء القدامى لا يستدعونه أصلا بل يبدأون بـ`initialize`.",
  "",
  "طلب الإصدار `2026-07-28` ينسخ ثلاث قيم من الجسم إلى الترويسات ويكرر رقم الإصدار داخل `params._meta`:",
  "",
  "```http",
  "POST /api/public-mcp HTTP/1.1",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "MCP-Protocol-Version: 2026-07-28",
  "Mcp-Method: tools/call",
  "Mcp-Name: list_games",
  "",
  "{",
  '  "jsonrpc": "2.0",',
  '  "id": 1,',
  '  "method": "tools/call",',
  '  "params": {',
  '    "name": "list_games",',
  '    "arguments": { "locale": "ar" },',
  '    "_meta": {',
  '      "io.modelcontextprotocol/protocolVersion": "2026-07-28",',
  '      "io.modelcontextprotocol/clientInfo": { "name": "YourClient", "version": "1.0.0" },',
  '      "io.modelcontextprotocol/clientCapabilities": {}',
  "    }",
  "  }",
  "}",
  "```",
  "",
  "ترويسة `Mcp-Name` مطلوبة مع `tools/call` فقط ويجب أن تطابق `params.name`. أي ترويسة تخالف الجسم تُرفض بالخطأ `-32020`، وأي إصدار غير مدعوم يُرفض بالخطأ `-32022` الذي يذكر ما تدعمه هذه النقطة.",
  "",
  "كل نتيجة في الإصدار `2026-07-28` تحمل `resultType: \"complete\"`. كما تحمل `tools/list` و`server/discover` الحقلين `ttlMs` و`cacheScope`: هذه النقطة تعيد الأدوات نفسها لكل المستخدمين، لذا قائمتها `cacheScope: \"public\"` ويمكن للذاكرات المشتركة تخزينها.",
  "",
  "## الأدوات",
  "",
  ...publicMcpToolLines("ar"),
  "",
  "## \u0623\u0645\u062b\u0644\u0629 \u0639\u0644\u0649 \u0627\u0644\u0623\u0633\u0626\u0644\u0629",
  "",
  '- "\u0627\u0639\u0631\u0636 \u0622\u062e\u0631 \u0623\u062e\u0628\u0627\u0631 Valorant \u0641\u064a EWC \u0645\u0639 \u0631\u0648\u0627\u0628\u0637 \u0627\u0644\u0645\u0648\u0642\u0639."',
  '- "\u0645\u0627 \u0627\u0644\u0623\u0646\u062f\u064a\u0629 \u0627\u0644\u0645\u062a\u0635\u062f\u0631\u0629 \u0641\u064a \u062a\u0631\u062a\u064a\u0628 \u0628\u0637\u0648\u0644\u0629 \u0623\u0646\u062f\u064a\u0629 EWC\u061f"',
  '- "\u0627\u0639\u0631\u0636 \u0644\u0648\u062d\u0629 \u062a\u0631\u062a\u064a\u0628 \u062a\u0648\u0642\u0639\u0627\u062a \u0645\u062c\u062a\u0645\u0639 EWC."',
  '- "\u0627\u0628\u062d\u062b \u0639\u0646 Team Falcons \u0648\u0627\u0639\u0631\u0636 \u0628\u064a\u0627\u0646\u0627\u062a \u0645\u0644\u0641\u0647 \u0627\u0644\u0639\u0627\u0645."',
  "",
  "\u062a\u0631\u062a\u064a\u0628 \u0628\u0637\u0648\u0644\u0629 \u0627\u0644\u0623\u0646\u062f\u064a\u0629 \u0648\u062a\u0631\u062a\u064a\u0628 \u062a\u0648\u0642\u0639\u0627\u062a \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0645\u062c\u0645\u0648\u0639\u062a\u0627 \u0628\u064a\u0627\u0646\u0627\u062a \u0645\u0646\u0641\u0635\u0644\u062a\u0627\u0646 \u0648\u0644\u0643\u0644 \u0645\u0646\u0647\u0645\u0627 \u0623\u062f\u0627\u062a\u0647\u0627.",
  "",
  "## إعداد العميل",
  "",
  "استخدم إعداد Streamable HTTP MCP الأصلي عندما يدعمه العميل.",
  "",
  "للعملاء الذين يدعمون stdio فقط، استخدم mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/public-mcp"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "لإعداد Codex عبر config.toml باستخدام stdio:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/public-mcp",',
  "]",
  "```",
  "",
  "للعملاء الذين يدعمون Streamable HTTP مباشرة:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/public-mcp"',
  "```",
  "",
  "أعد تشغيل عميل MCP بعد تغيير الإعدادات.",
  "",
  "## ملاحظات الأمان",
  "",
  "- هذه النقطة عامة وللقراءة فقط.",
  "- طلبات المتصفح يتم التحقق من Origin لها.",
  "- الطلبات محددة المعدل حسب عنوان IP الموثوق من الطرف. عند عدم وجود ترويسة IP موثوقة، تشترك الطلبات في حاوية معدل واحدة.",
  "- تقتصر الاستجابات على حقول الموقع العامة.",
].join("\n");

export const PUBLIC_MCP_COPY_PAGE_BY_LOCALE: Record<Locale, string> = {
  en: PUBLIC_MCP_COPY_PAGE_EN,
  ar: PUBLIC_MCP_COPY_PAGE_AR,
};

export const PUBLIC_MCP_COPY_PAGE = PUBLIC_MCP_COPY_PAGE_EN;

export function getPublicMcpCopyPage(locale: Locale) {
  return PUBLIC_MCP_COPY_PAGE_BY_LOCALE[locale];
}
