import type { Locale } from "@/lib/i18n";

const PUBLIC_MCP_COPY_PAGE_EN = [
  "# Public MCP",
  "",
  "The public MCP endpoint lets AI assistants read the same public Esports Community data that appears on the website, without a dashboard session or admin key.",
  "",
  "It is read-only and returns public website data intended for visitors.",
  "",
  "Docs page:",
  "",
  "```text",
  "https://esportscommunity.net/docs/mcp",
  "```",
  "",
  "## Endpoint",
  "",
  "Production:",
  "",
  "```text",
  "https://esportscommunity.net/api/public-mcp",
  "```",
  "",
  "Local development:",
  "",
  "```text",
  "http://localhost:3000/api/public-mcp",
  "```",
  "",
  "Required headers:",
  "",
  "```http",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "No bearer key is required. JSON-RPC batch arrays are rejected; send one MCP request at a time.",
  "",
  "## Tools",
  "",
  "- get_site_overview: public counts for games, tournaments, live/upcoming matches, published news, and live co-streams.",
  "- list_games: localized public game directory.",
  "- search_news: published news only, with query, locale, game/media, EWC, and limit filters.",
  "- get_tournament_status: public matches and standings for one tracked tournament.",
  "- list_tournaments: public active tournament summaries.",
  "- get_ewc_club_summary: public EWC club points, qualified games, wins, and region metadata.",
  "- list_co_streams: public co-stream groups, live-first.",
  "- search_teams: public team directory search with safe public fields.",
  "- search_players: public player directory search with safe public fields.",
  "- get_public_ewc_leaderboard: existing public prediction leaderboard projection.",
  "",
  "## Client Setup",
  "",
  "Use native Streamable HTTP MCP configuration when your client supports it.",
  "",
  "For stdio-only clients, use mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/public-mcp"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "For Codex config.toml stdio setup:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/public-mcp",',
  "]",
  "```",
  "",
  "For clients with native Streamable HTTP support:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/public-mcp"',
  "```",
  "",
  "Restart the MCP client after changing configuration.",
  "",
  "## Security Notes",
  "",
  "- This endpoint is public and read-only.",
  "- Browser-origin requests are origin-checked.",
  "- Requests are rate-limited by trusted edge IP. If no trusted IP header is present, requests share one fallback bucket.",
  "- Responses are limited to public website fields.",
].join("\n");

const PUBLIC_MCP_COPY_PAGE_AR = [
  "# خادم MCP العام",
  "",
  "نقطة نهاية MCP العامة تتيح لأدوات الذكاء الاصطناعي قراءة نفس بيانات Esports Community العامة الظاهرة في الموقع، بدون جلسة لوحة تحكم وبدون مفتاح إداري.",
  "",
  "هذه النقطة للقراءة فقط وتعرض بيانات عامة مخصصة لزوار الموقع.",
  "",
  "صفحة الشرح:",
  "",
  "```text",
  "https://esportscommunity.net/ar/docs/mcp",
  "```",
  "",
  "## نقطة النهاية",
  "",
  "الإنتاج:",
  "",
  "```text",
  "https://esportscommunity.net/api/public-mcp",
  "```",
  "",
  "التطوير المحلي:",
  "",
  "```text",
  "http://localhost:3000/api/public-mcp",
  "```",
  "",
  "الترويسات المطلوبة:",
  "",
  "```http",
  "Content-Type: application/json",
  "Accept: application/json, text/event-stream",
  "```",
  "",
  "لا تحتاج إلى مفتاح Bearer. يتم رفض طلبات JSON-RPC batch؛ أرسل طلب MCP واحدا في كل مرة.",
  "",
  "## الأدوات",
  "",
  "- get_site_overview: أعداد عامة للألعاب، البطولات، المباريات المباشرة والقادمة، الأخبار المنشورة، والبثوث المشتركة المباشرة.",
  "- list_games: دليل الألعاب العام حسب اللغة.",
  "- search_news: البحث في الأخبار المنشورة فقط مع فلاتر البحث، اللغة، اللعبة أو المنصة الإعلامية، EWC، والحد الأقصى.",
  "- get_tournament_status: المباريات والترتيب العام لبطولة متتبعة واحدة.",
  "- list_tournaments: ملخصات البطولات العامة النشطة.",
  "- get_ewc_club_summary: نقاط أندية EWC، الألعاب المتأهلة، الانتصارات، وبيانات المناطق.",
  "- list_co_streams: مجموعات البثوث المشتركة العامة، مع عرض المباشر أولا.",
  "- search_teams: البحث في دليل الفرق العام بحقول عامة آمنة.",
  "- search_players: البحث في دليل اللاعبين العام بحقول عامة آمنة.",
  "- get_public_ewc_leaderboard: عرض لوحة توقعات EWC العامة الحالية.",
  "",
  "## إعداد العميل",
  "",
  "استخدم إعداد Streamable HTTP MCP الأصلي عندما يدعمه العميل.",
  "",
  "للعملاء الذين يدعمون stdio فقط، استخدم mcp-remote:",
  "",
  "```json",
  "{",
  '  "mcpServers": {',
  '    "esports-community": {',
  '      "command": "npx",',
  '      "args": [',
  '        "-y",',
  '        "mcp-remote",',
  '        "https://esportscommunity.net/api/public-mcp"',
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "لإعداد Codex عبر config.toml باستخدام stdio:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  'command = "npx"',
  "args = [",
  '  "-y",',
  '  "mcp-remote",',
  '  "https://esportscommunity.net/api/public-mcp",',
  "]",
  "```",
  "",
  "للعملاء الذين يدعمون Streamable HTTP مباشرة:",
  "",
  "```toml",
  "[mcp_servers.esports_community_public]",
  "enabled = true",
  'url = "https://esportscommunity.net/api/public-mcp"',
  "```",
  "",
  "أعد تشغيل عميل MCP بعد تغيير الإعدادات.",
  "",
  "## ملاحظات الأمان",
  "",
  "- هذه النقطة عامة وللقراءة فقط.",
  "- طلبات المتصفح يتم التحقق من Origin لها.",
  "- الطلبات محددة المعدل حسب عنوان IP الموثوق من الطرف. عند عدم وجود ترويسة IP موثوقة، تشترك الطلبات في حاوية معدل واحدة.",
  "- تقتصر الاستجابات على حقول الموقع العامة.",
].join("\n");

export const PUBLIC_MCP_COPY_PAGE_BY_LOCALE: Record<Locale, string> = {
  en: PUBLIC_MCP_COPY_PAGE_EN,
  ar: PUBLIC_MCP_COPY_PAGE_AR,
};

export const PUBLIC_MCP_COPY_PAGE = PUBLIC_MCP_COPY_PAGE_EN;

export function getPublicMcpCopyPage(locale: Locale) {
  return PUBLIC_MCP_COPY_PAGE_BY_LOCALE[locale];
}
