-- PostgreSQL schema for the app-owned tables in the current SQLite database.
-- This intentionally preserves the app's current row shapes:
-- - *_json columns remain text
-- - datetime('now') values remain UTC-like text strings
-- - integer booleans remain integer flags
--
-- Better Auth tables are managed separately by Better Auth's PostgreSQL
-- migration command and are copied only after those tables exist.

CREATE TABLE IF NOT EXISTS tournaments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source       TEXT NOT NULL CHECK (source IN ('pandascore','startgg','liquipedia')),
  external_id  TEXT NOT NULL,
  game         TEXT,
  name         TEXT,
  url          TEXT,
  guild_id     TEXT NOT NULL,
  added_by     TEXT,
  ewc          INTEGER NOT NULL DEFAULT 0,
  active       INTEGER NOT NULL DEFAULT 1,
  archived_at  BIGINT,
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (source, external_id, guild_id)
);

ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS archived_at BIGINT;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS ewc INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS matches (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id  BIGINT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  source         TEXT NOT NULL,
  external_id    TEXT NOT NULL,
  name           TEXT,
  team_a         TEXT,
  team_b         TEXT,
  logo_a         TEXT,
  logo_b         TEXT,
  score_a        INTEGER DEFAULT 0,
  score_b        INTEGER DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled','running','finished')),
  scheduled_at   BIGINT,
  stream_platform TEXT,
  stream_url      TEXT,
  last_polled_at TEXT,
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (source, external_id)
);

-- Official per-match broadcast stream (the Liquipedia Special:Stream link, which
-- resolves the real channel); added for existing deployments.
ALTER TABLE matches ADD COLUMN IF NOT EXISTS stream_platform TEXT;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS stream_url TEXT;

CREATE INDEX IF NOT EXISTS idx_matches_status ON matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_tournament ON matches(tournament_id);

CREATE TABLE IF NOT EXISTS teams (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game           TEXT,
  pandascore_id  BIGINT UNIQUE,
  name           TEXT NOT NULL,
  slug           TEXT,
  acronym        TEXT,
  nationality    TEXT,
  image_url      TEXT,
  location       TEXT,
  modified_at    TEXT,
  raw_json       TEXT,
  last_seen_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

ALTER TABLE teams ADD COLUMN IF NOT EXISTS game TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS acronym TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS nationality TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS modified_at TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS raw_json TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS last_seen_at TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS updated_at TEXT;

CREATE INDEX IF NOT EXISTS idx_teams_game_name ON teams(game, name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_teams_game_slug ON teams(game, slug) WHERE slug IS NOT NULL;

CREATE TABLE IF NOT EXISTS players (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game                        TEXT,
  pandascore_id               BIGINT UNIQUE,
  name                        TEXT NOT NULL,
  slug                        TEXT,
  first_name                  TEXT,
  last_name                   TEXT,
  nationality                 TEXT,
  image_url                   TEXT,
  role                        TEXT,
  current_team_id             BIGINT REFERENCES teams(id) ON DELETE SET NULL,
  current_team_pandascore_id  BIGINT,
  current_team_name           TEXT,
  modified_at                 TEXT,
  raw_json                    TEXT,
  last_seen_at                TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  created_at                  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at                  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

ALTER TABLE players ADD COLUMN IF NOT EXISTS game TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS nationality TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS current_team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS current_team_pandascore_id BIGINT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS current_team_name TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS modified_at TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS raw_json TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_seen_at TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS updated_at TEXT;

CREATE INDEX IF NOT EXISTS idx_players_game_name ON players(game, name);
CREATE INDEX IF NOT EXISTS idx_players_current_team ON players(current_team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_game_slug ON players(game, slug) WHERE slug IS NOT NULL;

CREATE TABLE IF NOT EXISTS guild_settings (
  guild_id                                  TEXT PRIMARY KEY,
  schedule_channel_id                       TEXT,
  voice_channel_id                          TEXT,
  leaderboard_channel_id                    TEXT,
  leaderboard_message_id                    TEXT,
  updated_at                                TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  cc_wiki                                   TEXT,
  cc_page                                   TEXT,
  cc_channel_id                             TEXT,
  cc_message_id                             TEXT,
  cc_label                                  TEXT,
  audit_log_channel_id                      TEXT,
  cs_rankings_channel_id                    TEXT,
  cs_rankings_message_id                    TEXT,
  cs_rankings_region                        TEXT,
  cs_rankings_format                        TEXT,
  match_card_channel_id                     TEXT,
  match_card_message_id                     TEXT,
  ewc_predictions_channel_id                TEXT,
  ewc_predictions_leaderboard_channel_id    TEXT,
  ewc_predictions_leaderboard_message_id    TEXT,
  ewc_predictions_leaderboard_season        TEXT,
  ewc_predictions_mentions_channel_id       TEXT,
  ewc_predictions_mentions_message_id       TEXT,
  ewc_predictions_mentions_season           TEXT,
  ewc_news_channel_id                       TEXT,
  costream_announce_channel_id              TEXT,
  costream_announce_role_id                 TEXT
);
ALTER TABLE guild_settings ADD COLUMN IF NOT EXISTS costream_announce_channel_id TEXT;
ALTER TABLE guild_settings ADD COLUMN IF NOT EXISTS costream_announce_role_id TEXT;

CREATE TABLE IF NOT EXISTS game_leaderboards (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS game_voice_channels (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS game_match_cards (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS match_card_messages (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  match_id   BIGINT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game, match_id)
);

CREATE TABLE IF NOT EXISTS ewc_prediction_weeks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL DEFAULT '2026',
  week_key       TEXT NOT NULL,
  label          TEXT,
  start_at       BIGINT,
  end_at         BIGINT,
  open_at        BIGINT,
  close_at       BIGINT,
  score_after    BIGINT,
  status         TEXT NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open','closed','scored')),
  baseline_json  TEXT,
  final_json     TEXT,
  games_json     TEXT,
  results_json   TEXT,
  created_by     TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  scored_at      TEXT,
  open_announced_at TEXT,
  UNIQUE (guild_id, season, week_key)
);
ALTER TABLE ewc_prediction_weeks ADD COLUMN IF NOT EXISTS open_announced_at TEXT;

CREATE TABLE IF NOT EXISTS ewc_weekly_predictions (
  guild_id       TEXT NOT NULL,
  week_id        BIGINT NOT NULL REFERENCES ewc_prediction_weeks(id) ON DELETE CASCADE,
  user_id        TEXT NOT NULL,
  picks_json     TEXT NOT NULL,
  score          INTEGER,
  details_json   TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, week_id, user_id)
);

CREATE TABLE IF NOT EXISTS ewc_prediction_reminders (
  guild_id          TEXT NOT NULL,
  week_id           BIGINT NOT NULL REFERENCES ewc_prediction_weeks(id) ON DELETE CASCADE,
  game_key          TEXT NOT NULL,
  kind              TEXT NOT NULL,
  sent_at           TEXT,
  claim_token       TEXT,
  claim_expires_at  BIGINT,
  attempts          INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (guild_id, week_id, game_key, kind)
);

CREATE INDEX IF NOT EXISTS idx_ewc_weekly_predictions_week
  ON ewc_weekly_predictions(week_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_ewc_prediction_reminders_claim
  ON ewc_prediction_reminders(sent_at, claim_expires_at);

CREATE TABLE IF NOT EXISTS ewc_prediction_seasons (
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL DEFAULT '2026',
  label          TEXT,
  open_at        BIGINT,
  close_at       BIGINT,
  score_after    BIGINT,
  status         TEXT NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open','closed','scored')),
  top_size       INTEGER NOT NULL DEFAULT 10,
  best_weeks     INTEGER,
  final_json     TEXT,
  created_by     TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  scored_at      TEXT,
  PRIMARY KEY (guild_id, season)
);

CREATE TABLE IF NOT EXISTS ewc_season_predictions (
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  picks_json     TEXT NOT NULL,
  score          INTEGER,
  details_json   TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, season, user_id)
);

CREATE TABLE IF NOT EXISTS ewc_club_championship_snapshots (
  season          TEXT PRIMARY KEY,
  source_url      TEXT NOT NULL,
  standings_json  TEXT NOT NULL,
  prizepool_json  TEXT NOT NULL DEFAULT '[]',
  fetched_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_ewc_season_predictions_season
  ON ewc_season_predictions(guild_id, season, score DESC);
CREATE INDEX IF NOT EXISTS idx_ewc_club_championship_snapshots_fetched
  ON ewc_club_championship_snapshots(fetched_at DESC);

CREATE TABLE IF NOT EXISTS ewc_profile_links (
  auth_user_id     TEXT NOT NULL,
  discord_user_id  TEXT PRIMARY KEY,
  guild_id         TEXT NOT NULL,
  season           TEXT NOT NULL DEFAULT '2026',
  last_synced_at   TEXT,
  last_sync_error  TEXT,
  created_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_news_posts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Owned by EITHER a game (game_slug) OR a media channel (media_slug).
  game_slug         TEXT,
  media_slug        TEXT,
  locale            TEXT NOT NULL DEFAULT 'en' CHECK (locale IN ('en','ar')),
  content_mode      TEXT NOT NULL DEFAULT 'shared' CHECK (content_mode IN ('shared','translated')),
  default_locale    TEXT NOT NULL DEFAULT 'en' CHECK (default_locale IN ('en','ar')),
  title             TEXT NOT NULL,
  summary           TEXT NOT NULL DEFAULT '',
  body              TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  author_discord_id TEXT,
  author_name       TEXT,
  cover_image_url   TEXT,
  cover_placement   TEXT,
  ewc               INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  published_at      TEXT
);

-- Migration: add the EWC tag to pre-existing installs (idempotent; runs on boot).
ALTER TABLE ewc_news_posts ADD COLUMN IF NOT EXISTS ewc INTEGER NOT NULL DEFAULT 0;
-- Migration: media-channel ownership. game_slug becomes nullable so media posts can
-- omit it; media_slug names the owning channel when set.
ALTER TABLE ewc_news_posts ADD COLUMN IF NOT EXISTS media_slug TEXT;
ALTER TABLE ewc_news_posts ALTER COLUMN game_slug DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ewc_news_posts_game_status
  ON ewc_news_posts(game_slug, status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_ewc_news_posts_media_status
  ON ewc_news_posts(media_slug, status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_ewc_news_posts_status_updated
  ON ewc_news_posts(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS ewc_news_post_translations (
  post_id    BIGINT NOT NULL REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  locale     TEXT NOT NULL CHECK (locale IN ('en','ar')),
  title      TEXT NOT NULL DEFAULT '',
  summary    TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (post_id, locale)
);

-- A post can credit multiple authors; name/avatar are snapshotted at save time
-- (avatar from the author's Better Auth login, null if they never signed in).
CREATE TABLE IF NOT EXISTS ewc_news_post_authors (
  post_id    BIGINT NOT NULL REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  discord_id TEXT NOT NULL,
  name       TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (post_id, discord_id)
);

CREATE TABLE IF NOT EXISTS ewc_news_discord_posts (
  post_id    BIGINT PRIMARY KEY REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  guild_id   TEXT,
  channel_id TEXT,
  message_id TEXT,
  posted_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_games (
  slug               TEXT PRIMARY KEY,
  title_json         TEXT NOT NULL,
  description_json   TEXT NOT NULL,
  status_json        TEXT NOT NULL,
  owner_json         TEXT NOT NULL,
  focus_json         TEXT NOT NULL DEFAULT '[]',
  discord_channel_id TEXT,
  sort_order         INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_ewc_games_sort ON ewc_games(sort_order, slug);

CREATE TABLE IF NOT EXISTS ewc_media_channels (
  slug               TEXT PRIMARY KEY,
  name_json          TEXT NOT NULL,
  description_json   TEXT NOT NULL,
  logo_url           TEXT,
  links_json         TEXT NOT NULL DEFAULT '[]',
  discord_channel_id TEXT,
  game_slug          TEXT,
  sort_order         INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- Migration: media auto-post target + related game on pre-existing installs.
ALTER TABLE ewc_media_channels ADD COLUMN IF NOT EXISTS discord_channel_id TEXT;
ALTER TABLE ewc_media_channels ADD COLUMN IF NOT EXISTS game_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_ewc_media_channels_sort
  ON ewc_media_channels(sort_order, slug);

-- Side table mapping a media channel to the Discord message that announces it.
-- One row per channel (single-guild); cleaned up explicitly in deleteEwcMediaChannel.
CREATE TABLE IF NOT EXISTS ewc_media_discord_posts (
  slug       TEXT PRIMARY KEY,
  guild_id   TEXT,
  channel_id TEXT,
  message_id TEXT,
  posted_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_rate_limits (
  key           TEXT PRIMARY KEY,
  window_start  BIGINT NOT NULL,
  amount        INTEGER NOT NULL
);

-- Community comments on news posts (one-level threads; soft delete). See the
-- SQLite schema in src/db/index.js for the threading/visibility notes.
CREATE TABLE IF NOT EXISTS post_comments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id           BIGINT NOT NULL REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES post_comments(id) ON DELETE SET NULL,
  root_comment_id   BIGINT REFERENCES post_comments(id) ON DELETE SET NULL,
  auth_user_id      TEXT NOT NULL,
  discord_user_id   TEXT NOT NULL,
  author_name       TEXT NOT NULL DEFAULT '',
  author_avatar_url TEXT,
  body              TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'visible'
                    CHECK (status IN ('visible','pending','hidden','rejected','deleted')),
  flag_reason_json  TEXT,
  auto_approve_at   BIGINT,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  edited_at         TEXT,
  deleted_at        TEXT,
  deleted_by        TEXT
);
ALTER TABLE post_comments ADD COLUMN IF NOT EXISTS author_avatar_url TEXT;
CREATE INDEX IF NOT EXISTS idx_post_comments_post ON post_comments(post_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_post_comments_root ON post_comments(root_comment_id, created_at);
CREATE INDEX IF NOT EXISTS idx_post_comments_autoapprove ON post_comments(status, auto_approve_at);

CREATE TABLE IF NOT EXISTS post_likes (
  post_id         BIGINT NOT NULL REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  discord_user_id TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (post_id, discord_user_id)
);

CREATE TABLE IF NOT EXISTS comment_likes (
  comment_id      BIGINT NOT NULL REFERENCES post_comments(id) ON DELETE CASCADE,
  discord_user_id TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (comment_id, discord_user_id)
);

CREATE TABLE IF NOT EXISTS comment_moderation_actions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id           BIGINT NOT NULL,
  moderator_discord_id TEXT NOT NULL,
  moderator_name       TEXT,
  action               TEXT NOT NULL,
  reason               TEXT,
  created_at           TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_comment_mod_actions ON comment_moderation_actions(comment_id, created_at);

CREATE TABLE IF NOT EXISTS comment_reports (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id            BIGINT NOT NULL REFERENCES post_comments(id) ON DELETE CASCADE,
  reporter_discord_id   TEXT NOT NULL,
  reporter_auth_user_id TEXT,
  reason                TEXT NOT NULL CHECK (reason IN ('spam','harassment','hate','sexual','other')),
  detail                TEXT NOT NULL DEFAULT '',
  status                TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved','dismissed')),
  created_at            TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (comment_id, reporter_discord_id)
);
CREATE INDEX IF NOT EXISTS idx_comment_reports_comment ON comment_reports(comment_id, status);
CREATE INDEX IF NOT EXISTS idx_comment_reports_open ON comment_reports(status, created_at DESC);

CREATE TABLE IF NOT EXISTS community_user_blocks (
  discord_user_id TEXT PRIMARY KEY,
  blocked_by      TEXT NOT NULL,
  blocked_by_name TEXT,
  reason          TEXT,
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS partner_inquiries (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_name TEXT NOT NULL,
  contact_name      TEXT NOT NULL,
  email             TEXT NOT NULL,
  website_url       TEXT,
  interest          TEXT NOT NULL CHECK (interest IN ('open_source_partner','prediction_partner','event_prize_later','other')),
  message           TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','contacted','approved','declined','converted')),
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_partner_inquiries_status
  ON partner_inquiries(status, created_at DESC);

CREATE TABLE IF NOT EXISTS partners (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  logo_url    TEXT,
  website_url TEXT,
  summary     TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_partners_status
  ON partners(status, name);

CREATE TABLE IF NOT EXISTS partner_campaigns (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id        BIGINT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  kind              TEXT NOT NULL CHECK (kind IN ('homepage','footer','predictions','leaderboard','tournament')),
  target            TEXT NOT NULL DEFAULT '',
  title             TEXT NOT NULL DEFAULT '',
  note              TEXT NOT NULL DEFAULT '',
  start_at          BIGINT,
  end_at            BIGINT,
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','ended')),
  payment_method    TEXT NOT NULL DEFAULT 'github_sponsors' CHECK (payment_method IN ('github_sponsors','bank_transfer','paypal','other','waived')),
  payment_status    TEXT NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','pending','paid')),
  payment_reference TEXT,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_partner_campaigns_active
  ON partner_campaigns(kind, target, status, start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_partner_campaigns_partner
  ON partner_campaigns(partner_id);

CREATE TABLE IF NOT EXISTS ewc_admins (
  discord_id   TEXT PRIMARY KEY,
  display_name TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_admin_game_scopes (
  discord_id TEXT NOT NULL,
  game_slug  TEXT NOT NULL,
  PRIMARY KEY (discord_id, game_slug)
);

CREATE TABLE IF NOT EXISTS ewc_admin_media_scopes (
  discord_id TEXT NOT NULL,
  media_slug TEXT NOT NULL,
  PRIMARY KEY (discord_id, media_slug)
);

CREATE TABLE IF NOT EXISTS ewc_admin_audit_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id     TEXT NOT NULL,
  actor_name   TEXT,
  action       TEXT NOT NULL,
  target       TEXT,
  details      TEXT,
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created
  ON ewc_admin_audit_log(created_at DESC);

CREATE TABLE IF NOT EXISTS ewc_mcp_keys (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash          TEXT NOT NULL UNIQUE,
  key_prefix        TEXT NOT NULL,
  label             TEXT NOT NULL DEFAULT '',
  owner_discord_id  TEXT NOT NULL,
  owner_name        TEXT,
  tools_json        TEXT NOT NULL DEFAULT '[]',
  game_scopes_json  TEXT NOT NULL DEFAULT '[]',
  media_scopes_json TEXT NOT NULL DEFAULT '[]',
  expires_at        BIGINT,
  revoked_at        TEXT,
  last_used_at      TEXT,
  created_by        TEXT,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_ewc_mcp_keys_owner
  ON ewc_mcp_keys(owner_discord_id, revoked_at);

CREATE TABLE IF NOT EXISTS ewc_mcp_write_receipts (
  key_id          BIGINT NOT NULL,
  tool_name       TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  result_json     TEXT,
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  completed_at    TEXT,
  PRIMARY KEY (key_id, tool_name, idempotency_key)
);

-- Admin-curated live-stream / co-stream channels (Twitch, Kick, YouTube, SOOP).
-- A channel is attached at one SCOPE: 'game' (every match of game_slug),
-- 'team' (every match a team plays, keyed by normalized team_key), 'match'
-- (one match by external id), or 'ewc' (the official EWC co-stream list).
-- Scope-key columns default to '' (not NULL) so the UNIQUE constraint behaves
-- identically on SQLite and Postgres. Live status lives in a separate table.
CREATE TABLE IF NOT EXISTS stream_channels (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform          TEXT NOT NULL CHECK (platform IN ('twitch','kick','youtube','soop')),
  handle            TEXT NOT NULL,
  label             TEXT NOT NULL DEFAULT '',
  scope             TEXT NOT NULL CHECK (scope IN ('game','team','match','ewc')),
  creator_key       TEXT NOT NULL DEFAULT '',
  game_slug         TEXT NOT NULL DEFAULT '',
  game_slugs        TEXT NOT NULL DEFAULT '[]',
  team_key          TEXT NOT NULL DEFAULT '',
  match_external_id TEXT NOT NULL DEFAULT '',
  language          TEXT NOT NULL DEFAULT '',
  sort_order        INTEGER NOT NULL DEFAULT 0,
  is_default        INTEGER NOT NULL DEFAULT 0,
  active            INTEGER NOT NULL DEFAULT 1,
  added_by          TEXT,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (platform, handle, scope, game_slug, team_key, match_external_id)
);
ALTER TABLE stream_channels ADD COLUMN IF NOT EXISTS creator_key TEXT NOT NULL DEFAULT '';
ALTER TABLE stream_channels ADD COLUMN IF NOT EXISTS game_slugs TEXT NOT NULL DEFAULT '[]';
ALTER TABLE stream_channels ADD COLUMN IF NOT EXISTS is_default INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_stream_channels_scope ON stream_channels(scope, active);
CREATE INDEX IF NOT EXISTS idx_stream_channels_game  ON stream_channels(game_slug, active);
CREATE INDEX IF NOT EXISTS idx_stream_channels_creator ON stream_channels(creator_key, active);
CREATE INDEX IF NOT EXISTS idx_stream_channels_team  ON stream_channels(team_key, active);

-- Live status per platform+handle, refreshed by the stream-status poller. Keyed by
-- platform+handle (NOT channel id) so multiple channel rows sharing a handle share
-- one status row. is_live 0/1; timestamps are unix seconds.
CREATE TABLE IF NOT EXISTS stream_channel_status (
  platform      TEXT    NOT NULL,
  handle        TEXT    NOT NULL,
  is_live       INTEGER NOT NULL DEFAULT 0,
  title         TEXT,
  viewer_count  INTEGER,
  category      TEXT,
  thumbnail_url TEXT,
  video_id      TEXT,
  started_at    BIGINT,
  checked_at    BIGINT,
  updated_at    TEXT    NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (platform, handle)
);
CREATE INDEX IF NOT EXISTS idx_stream_status_live ON stream_channel_status(is_live);
-- Live VIDEO id (YouTube): the embed needs it — youtube.com/embed/<video_id>.
ALTER TABLE stream_channel_status ADD COLUMN IF NOT EXISTS video_id TEXT;

-- Persistent creator-level go-live cooldown. This prevents duplicate Discord
-- announcements when the same streamer is live on multiple platforms and one
-- platform status arrives later or the bot restarts between polls.
CREATE TABLE IF NOT EXISTS stream_creator_announce_state (
  creator_key     TEXT PRIMARY KEY,
  announced_at    BIGINT NOT NULL,
  platform        TEXT,
  handle          TEXT,
  title           TEXT,
  live_started_at BIGINT,
  updated_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- Follows + notifications. A member (by Discord id) follows games / tournaments /
-- teams / players; match transitions fan out one notification row per follower.
-- user_notifications is BOTH the site inbox and the Discord-DM outbox (dm_status).
-- entity_key: game -> slug, tournament -> tournaments.id::text,
-- team -> normalized team name, player -> players.id::text.
CREATE TABLE IF NOT EXISTS user_follows (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_user_id TEXT NOT NULL,
  entity_type     TEXT NOT NULL CHECK (entity_type IN ('game','tournament','team','player')),
  entity_key      TEXT NOT NULL,
  entity_label    TEXT NOT NULL DEFAULT '',
  entity_ref      TEXT NOT NULL DEFAULT '',
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (discord_user_id, entity_type, entity_key)
);
CREATE INDEX IF NOT EXISTS idx_user_follows_entity ON user_follows(entity_type, entity_key);
CREATE INDEX IF NOT EXISTS idx_user_follows_user   ON user_follows(discord_user_id);

CREATE TABLE IF NOT EXISTS user_notification_prefs (
  discord_user_id     TEXT PRIMARY KEY,
  dm_enabled          INTEGER NOT NULL DEFAULT 1,
  notify_match_start  INTEGER NOT NULL DEFAULT 1,
  notify_match_result INTEGER NOT NULL DEFAULT 1,
  updated_at          TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS user_notifications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_user_id TEXT NOT NULL,
  type            TEXT NOT NULL CHECK (type IN ('match_start','match_result')),
  match_id        BIGINT,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL DEFAULT '',
  url             TEXT NOT NULL DEFAULT '',
  dedupe_key      TEXT NOT NULL,
  read_at         TEXT,
  dm_status       TEXT NOT NULL DEFAULT 'skipped' CHECK (dm_status IN ('pending','sent','skipped','failed')),
  created_at      TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (discord_user_id, dedupe_key)
);
CREATE INDEX IF NOT EXISTS idx_user_notifications_user ON user_notifications(discord_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_notifications_dm   ON user_notifications(dm_status);

-- Privacy-friendly first-party website analytics. visitor_id/session_id are
-- browser-generated random ids; raw IP addresses are intentionally not stored.
CREATE TABLE IF NOT EXISTS web_analytics_events (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id       TEXT NOT NULL,
  session_id       TEXT NOT NULL,
  event_type       TEXT NOT NULL CHECK (event_type IN ('pageview','engagement')),
  path             TEXT NOT NULL,
  referrer         TEXT,
  country          TEXT,
  user_agent       TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  occurred_at      BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_web_analytics_occurred
  ON web_analytics_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_web_analytics_visitor
  ON web_analytics_events(visitor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_web_analytics_session
  ON web_analytics_events(session_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_web_analytics_country
  ON web_analytics_events(country, occurred_at DESC);

-- Liquipedia entity enrichment: page link, parsed fragment (infobox/roster HTML),
-- extracted facts JSON, and freshness stamp. pandascore_id becomes nullable so
-- Liquipedia-only entities (battle-royale games, TFT) can exist without a
-- PandaScore counterpart.
ALTER TABLE teams ALTER COLUMN pandascore_id DROP NOT NULL;
ALTER TABLE players ALTER COLUMN pandascore_id DROP NOT NULL;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS liquipedia_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS liquipedia_raw TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS liquipedia_facts TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS liquipedia_parsed_at TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS liquipedia_url TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS liquipedia_raw TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS liquipedia_facts TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS liquipedia_parsed_at TEXT;

-- Roster precedence: set when a successfully parsed Liquipedia roster confirmed
-- the player's team. While present, PandaScore syncs must not overwrite
-- current_team_* (Liquipedia rosters are fresher than PandaScore's team data).
ALTER TABLE players ADD COLUMN IF NOT EXISTS current_team_verified_at TEXT;

-- Standings for tournaments whose Liquipedia format has no head-to-head matches
-- (battle-royale events, TFT groups). Replaced wholesale on each refresh.
CREATE TABLE IF NOT EXISTS tournament_standings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id BIGINT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  section       TEXT NOT NULL DEFAULT '',
  section_order INTEGER NOT NULL DEFAULT 0,
  rank          INTEGER NOT NULL,
  team          TEXT NOT NULL,
  logo          TEXT,
  points        TEXT NOT NULL DEFAULT '',
  extra         TEXT NOT NULL DEFAULT '',
  updated_at    TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
ALTER TABLE tournament_standings ADD COLUMN IF NOT EXISTS section_order INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_tournament_standings_tournament
  ON tournament_standings(tournament_id, section_order, rank);
