-- PostgreSQL schema for the app-owned tables in the current SQLite database.
-- This intentionally preserves the app's current row shapes:
-- - *_json columns remain text
-- - datetime('now') values remain UTC-like text strings
-- - integer booleans remain integer flags
--
-- Better Auth tables are managed separately by Better Auth's PostgreSQL
-- migration command and are copied only after those tables exist.

CREATE TABLE IF NOT EXISTS tournaments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source       TEXT NOT NULL CHECK (source IN ('pandascore','startgg','liquipedia')),
  external_id  TEXT NOT NULL,
  game         TEXT,
  name         TEXT,
  url          TEXT,
  guild_id     TEXT NOT NULL,
  added_by     TEXT,
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (source, external_id, guild_id)
);

CREATE TABLE IF NOT EXISTS matches (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id  BIGINT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  source         TEXT NOT NULL,
  external_id    TEXT NOT NULL,
  name           TEXT,
  team_a         TEXT,
  team_b         TEXT,
  logo_a         TEXT,
  logo_b         TEXT,
  score_a        INTEGER DEFAULT 0,
  score_b        INTEGER DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled','running','finished')),
  scheduled_at   BIGINT,
  last_polled_at TEXT,
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_matches_status ON matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_tournament ON matches(tournament_id);

CREATE TABLE IF NOT EXISTS guild_settings (
  guild_id                                  TEXT PRIMARY KEY,
  schedule_channel_id                       TEXT,
  voice_channel_id                          TEXT,
  leaderboard_channel_id                    TEXT,
  leaderboard_message_id                    TEXT,
  updated_at                                TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  cc_wiki                                   TEXT,
  cc_page                                   TEXT,
  cc_channel_id                             TEXT,
  cc_message_id                             TEXT,
  cc_label                                  TEXT,
  audit_log_channel_id                      TEXT,
  cs_rankings_channel_id                    TEXT,
  cs_rankings_message_id                    TEXT,
  cs_rankings_region                        TEXT,
  cs_rankings_format                        TEXT,
  match_card_channel_id                     TEXT,
  match_card_message_id                     TEXT,
  ewc_predictions_channel_id                TEXT,
  ewc_predictions_leaderboard_channel_id    TEXT,
  ewc_predictions_leaderboard_message_id    TEXT,
  ewc_predictions_leaderboard_season        TEXT,
  ewc_predictions_mentions_channel_id       TEXT,
  ewc_predictions_mentions_message_id       TEXT,
  ewc_predictions_mentions_season           TEXT,
  ewc_news_channel_id                       TEXT
);

CREATE TABLE IF NOT EXISTS game_leaderboards (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS game_voice_channels (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS game_match_cards (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game)
);

CREATE TABLE IF NOT EXISTS match_card_messages (
  guild_id   TEXT NOT NULL,
  game       TEXT NOT NULL,
  match_id   BIGINT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, game, match_id)
);

CREATE TABLE IF NOT EXISTS ewc_prediction_weeks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL DEFAULT '2026',
  week_key       TEXT NOT NULL,
  label          TEXT,
  start_at       BIGINT,
  end_at         BIGINT,
  open_at        BIGINT,
  close_at       BIGINT,
  score_after    BIGINT,
  status         TEXT NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open','closed','scored')),
  baseline_json  TEXT,
  final_json     TEXT,
  games_json     TEXT,
  results_json   TEXT,
  created_by     TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  scored_at      TEXT,
  UNIQUE (guild_id, season, week_key)
);

CREATE TABLE IF NOT EXISTS ewc_weekly_predictions (
  guild_id       TEXT NOT NULL,
  week_id        BIGINT NOT NULL REFERENCES ewc_prediction_weeks(id) ON DELETE CASCADE,
  user_id        TEXT NOT NULL,
  picks_json     TEXT NOT NULL,
  score          INTEGER,
  details_json   TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, week_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_ewc_weekly_predictions_week
  ON ewc_weekly_predictions(week_id, score DESC);

CREATE TABLE IF NOT EXISTS ewc_prediction_seasons (
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL DEFAULT '2026',
  label          TEXT,
  open_at        BIGINT,
  close_at       BIGINT,
  score_after    BIGINT,
  status         TEXT NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open','closed','scored')),
  top_size       INTEGER NOT NULL DEFAULT 10,
  best_weeks     INTEGER,
  final_json     TEXT,
  created_by     TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  scored_at      TEXT,
  PRIMARY KEY (guild_id, season)
);

CREATE TABLE IF NOT EXISTS ewc_season_predictions (
  guild_id       TEXT NOT NULL,
  season         TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  picks_json     TEXT NOT NULL,
  score          INTEGER,
  details_json   TEXT,
  created_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (guild_id, season, user_id)
);

CREATE INDEX IF NOT EXISTS idx_ewc_season_predictions_season
  ON ewc_season_predictions(guild_id, season, score DESC);

CREATE TABLE IF NOT EXISTS ewc_profile_links (
  auth_user_id     TEXT NOT NULL,
  discord_user_id  TEXT PRIMARY KEY,
  guild_id         TEXT NOT NULL,
  season           TEXT NOT NULL DEFAULT '2026',
  last_synced_at   TEXT,
  last_sync_error  TEXT,
  created_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_news_posts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_slug         TEXT NOT NULL,
  locale            TEXT NOT NULL DEFAULT 'en' CHECK (locale IN ('en','ar')),
  content_mode      TEXT NOT NULL DEFAULT 'shared' CHECK (content_mode IN ('shared','translated')),
  default_locale    TEXT NOT NULL DEFAULT 'en' CHECK (default_locale IN ('en','ar')),
  title             TEXT NOT NULL,
  summary           TEXT NOT NULL DEFAULT '',
  body              TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  author_discord_id TEXT,
  author_name       TEXT,
  cover_image_url   TEXT,
  cover_placement   TEXT,
  created_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  published_at      TEXT
);

CREATE INDEX IF NOT EXISTS idx_ewc_news_posts_game_status
  ON ewc_news_posts(game_slug, status, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_ewc_news_posts_status_updated
  ON ewc_news_posts(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS ewc_news_post_translations (
  post_id    BIGINT NOT NULL REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  locale     TEXT NOT NULL CHECK (locale IN ('en','ar')),
  title      TEXT NOT NULL DEFAULT '',
  summary    TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (post_id, locale)
);

CREATE TABLE IF NOT EXISTS ewc_news_discord_posts (
  post_id    BIGINT PRIMARY KEY REFERENCES ewc_news_posts(id) ON DELETE CASCADE,
  guild_id   TEXT,
  channel_id TEXT,
  message_id TEXT,
  posted_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_games (
  slug               TEXT PRIMARY KEY,
  title_json         TEXT NOT NULL,
  description_json   TEXT NOT NULL,
  status_json        TEXT NOT NULL,
  owner_json         TEXT NOT NULL,
  focus_json         TEXT NOT NULL DEFAULT '[]',
  discord_channel_id TEXT,
  sort_order         INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at         TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_ewc_games_sort ON ewc_games(sort_order, slug);

CREATE TABLE IF NOT EXISTS ewc_media_channels (
  slug             TEXT PRIMARY KEY,
  name_json        TEXT NOT NULL,
  description_json TEXT NOT NULL,
  logo_url         TEXT,
  links_json       TEXT NOT NULL DEFAULT '[]',
  sort_order       INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_ewc_media_channels_sort
  ON ewc_media_channels(sort_order, slug);

CREATE TABLE IF NOT EXISTS ewc_rate_limits (
  key           TEXT PRIMARY KEY,
  window_start  BIGINT NOT NULL,
  amount        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ewc_admins (
  discord_id   TEXT PRIMARY KEY,
  display_name TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS ewc_admin_game_scopes (
  discord_id TEXT NOT NULL,
  game_slug  TEXT NOT NULL,
  PRIMARY KEY (discord_id, game_slug)
);

CREATE TABLE IF NOT EXISTS ewc_admin_media_scopes (
  discord_id TEXT NOT NULL,
  media_slug TEXT NOT NULL,
  PRIMARY KEY (discord_id, media_slug)
);

CREATE TABLE IF NOT EXISTS ewc_admin_audit_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id     TEXT NOT NULL,
  actor_name   TEXT,
  action       TEXT NOT NULL,
  target       TEXT,
  details      TEXT,
  created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created
  ON ewc_admin_audit_log(created_at DESC);
